catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.14
  vitest: npm:@voidzero-dev/vite-plus-test@latest
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@posthog/cli"
  - better-sqlite3
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
