import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    plugins: ["oxc", "typescript", "unicorn", "react", "node", "jsdoc", "import"],
    jsPlugins: [
      "@nuxt/eslint-plugin",
      "eslint-plugin-antfu",
      "eslint-plugin-unused-imports",
      "eslint-plugin-eslint-comments",
      "eslint-plugin-command",
      "eslint-plugin-perfectionist",
      "@stylistic/eslint-plugin",
      "eslint-plugin-regexp",
    ],
    categories: {
      correctness: "warn",
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    env: {
      builtin: true,
      es2026: true,
      browser: true,
      node: true,
    },
    globals: {
      $fetch: "readonly",
      asyncComputed: "readonly",
      autoResetRef: "readonly",
      computedAsync: "readonly",
      computedEager: "readonly",
      computedInject: "readonly",
      computedWithControl: "readonly",
      controlledComputed: "readonly",
      controlledRef: "readonly",
      createEventHook: "readonly",
      createGlobalState: "readonly",
      createInjectionState: "readonly",
      createReactiveFn: "readonly",
      createRef: "readonly",
      createReusableTemplate: "readonly",
      createSharedComposable: "readonly",
      createTemplatePromise: "readonly",
      createUnrefFn: "readonly",
      debouncedRef: "readonly",
      debouncedWatch: "readonly",
      eagerComputed: "readonly",
      extendRef: "readonly",
      ignorableWatch: "readonly",
      injectLocal: "readonly",
      isDefined: "readonly",
      makeDestructurable: "readonly",
      onClickOutside: "readonly",
      onElementRemoval: "readonly",
      onKeyStroke: "readonly",
      onLongPress: "readonly",
      onStartTyping: "readonly",
      pausableWatch: "readonly",
      provideLocal: "readonly",
      reactify: "readonly",
      reactifyObject: "readonly",
      reactiveComputed: "readonly",
      reactiveOmit: "readonly",
      reactivePick: "readonly",
      refAutoReset: "readonly",
      refDebounced: "readonly",
      refDefault: "readonly",
      refManualReset: "readonly",
      refThrottled: "readonly",
      refWithControl: "readonly",
      syncRef: "readonly",
      syncRefs: "readonly",
      templateRef: "readonly",
      throttledRef: "readonly",
      throttledWatch: "readonly",
      toReactive: "readonly",
      tryOnBeforeMount: "readonly",
      tryOnBeforeUnmount: "readonly",
      tryOnMounted: "readonly",
      tryOnScopeDispose: "readonly",
      tryOnUnmounted: "readonly",
      unrefElement: "readonly",
      until: "readonly",
      useActiveElement: "readonly",
      useArrayDifference: "readonly",
      useArrayEvery: "readonly",
      useArrayFilter: "readonly",
      useArrayFind: "readonly",
      useArrayFindIndex: "readonly",
      useArrayFindLast: "readonly",
      useArrayIncludes: "readonly",
      useArrayJoin: "readonly",
      useArrayMap: "readonly",
      useArrayReduce: "readonly",
      useArraySome: "readonly",
      useArrayUnique: "readonly",
      useAsyncQueue: "readonly",
      useAsyncState: "readonly",
      useBase64: "readonly",
      useBattery: "readonly",
      useBluetooth: "readonly",
      useBreakpoints: "readonly",
      useBroadcastChannel: "readonly",
      useBrowserLocation: "readonly",
      useCached: "readonly",
      useClipboard: "readonly",
      useClipboardItems: "readonly",
      useCloned: "readonly",
      useConfirmDialog: "readonly",
      useCountdown: "readonly",
      useCounter: "readonly",
      useCssSupports: "readonly",
      useCssVar: "readonly",
      useCurrentElement: "readonly",
      useCycleList: "readonly",
      useDark: "readonly",
      useDateFormat: "readonly",
      useDebounce: "readonly",
      useDebouncedRefHistory: "readonly",
      useDebounceFn: "readonly",
      useDeviceMotion: "readonly",
      useDeviceOrientation: "readonly",
      useDevicePixelRatio: "readonly",
      useDevicesList: "readonly",
      useDisplayMedia: "readonly",
      useDocumentVisibility: "readonly",
      useDraggable: "readonly",
      useDropZone: "readonly",
      useElementBounding: "readonly",
      useElementByPoint: "readonly",
      useElementHover: "readonly",
      useElementSize: "readonly",
      useElementVisibility: "readonly",
      useEventBus: "readonly",
      useEventListener: "readonly",
      useEventSource: "readonly",
      useEyeDropper: "readonly",
      useFavicon: "readonly",
      useFileDialog: "readonly",
      useFileSystemAccess: "readonly",
      useFocus: "readonly",
      useFocusWithin: "readonly",
      useFps: "readonly",
      useFullscreen: "readonly",
      useGamepad: "readonly",
      useGeolocation: "readonly",
      useIdle: "readonly",
      useInfiniteScroll: "readonly",
      useIntersectionObserver: "readonly",
      useInterval: "readonly",
      useIntervalFn: "readonly",
      useKeyModifier: "readonly",
      useLastChanged: "readonly",
      useLocalStorage: "readonly",
      useMagicKeys: "readonly",
      useManualRefHistory: "readonly",
      useMediaControls: "readonly",
      useMediaQuery: "readonly",
      useMemoize: "readonly",
      useMemory: "readonly",
      useMounted: "readonly",
      useMouse: "readonly",
      useMouseInElement: "readonly",
      useMousePressed: "readonly",
      useMutationObserver: "readonly",
      useNavigatorLanguage: "readonly",
      useNetwork: "readonly",
      useNow: "readonly",
      useObjectUrl: "readonly",
      useOffsetPagination: "readonly",
      useOnline: "readonly",
      usePageLeave: "readonly",
      useParallax: "readonly",
      useParentElement: "readonly",
      usePerformanceObserver: "readonly",
      usePermission: "readonly",
      usePointer: "readonly",
      usePointerLock: "readonly",
      usePointerSwipe: "readonly",
      usePreferredColorScheme: "readonly",
      usePreferredContrast: "readonly",
      usePreferredDark: "readonly",
      usePreferredLanguages: "readonly",
      usePreferredReducedMotion: "readonly",
      usePreferredReducedTransparency: "readonly",
      usePrevious: "readonly",
      useRafFn: "readonly",
      useRefHistory: "readonly",
      useResizeObserver: "readonly",
      useScreenOrientation: "readonly",
      useScreenSafeArea: "readonly",
      useScriptTag: "readonly",
      useScrollLock: "readonly",
      useSessionStorage: "readonly",
      useShare: "readonly",
      useSorted: "readonly",
      useSpeechRecognition: "readonly",
      useSpeechSynthesis: "readonly",
      useSSRWidth: "readonly",
      useStepper: "readonly",
      useStorageAsync: "readonly",
      useStyleTag: "readonly",
      useSupported: "readonly",
      useSwipe: "readonly",
      useTemplateRefsList: "readonly",
      useTextareaAutosize: "readonly",
      useTextDirection: "readonly",
      useTextSelection: "readonly",
      useThrottle: "readonly",
      useThrottledRefHistory: "readonly",
      useThrottleFn: "readonly",
      useTimeAgo: "readonly",
      useTimeAgoIntl: "readonly",
      useTimeout: "readonly",
      useTimeoutFn: "readonly",
      useTimeoutPoll: "readonly",
      useTimestamp: "readonly",
      useTitle: "readonly",
      useToggle: "readonly",
      useToNumber: "readonly",
      useToString: "readonly",
      useTransition: "readonly",
      useUrlSearchParams: "readonly",
      useUserMedia: "readonly",
      useVibrate: "readonly",
      useVirtualList: "readonly",
      useVModel: "readonly",
      useVModels: "readonly",
      useWakeLock: "readonly",
      useWebNotification: "readonly",
      useWebSocket: "readonly",
      useWebWorker: "readonly",
      useWebWorkerFn: "readonly",
      useWindowFocus: "readonly",
      useWindowScroll: "readonly",
      useWindowSize: "readonly",
      watchArray: "readonly",
      watchAtMost: "readonly",
      watchDebounced: "readonly",
      watchDeep: "readonly",
      watchIgnorable: "readonly",
      watchImmediate: "readonly",
      watchOnce: "readonly",
      watchPausable: "readonly",
      watchThrottled: "readonly",
      watchTriggerable: "readonly",
      watchWithFilter: "readonly",
      whenever: "readonly",
      useElementStyle: "readonly",
      useElementTransform: "readonly",
      useMotion: "readonly",
      useMotionProperties: "readonly",
      useMotionVariants: "readonly",
      useHeaderHeight: "readonly",
      useAnimatedDialog: "readonly",
      useEasings: "readonly",
      useFormatDate: "readonly",
      useImgOnError: "readonly",
      useScrollGallery: "readonly",
      useServicesList: "readonly",
      useTouchHandler: "readonly",
      queryCollection: "readonly",
      queryCollectionItemSurroundings: "readonly",
      queryCollectionNavigation: "readonly",
      queryCollectionSearchSections: "readonly",
      useImage: "readonly",
      defineAppConfig: "readonly",
      __buildAssetsURL: "readonly",
      __publicAssetsURL: "readonly",
      useColorMode: "readonly",
      defineLocale: "readonly",
      extendLocale: "readonly",
      defineShortcuts: "readonly",
      extractShortcuts: "readonly",
      avatarGroupInjectionKey: "readonly",
      useAvatarGroup: "readonly",
      useComponentIcons: "readonly",
      useContentSearch: "readonly",
      useEditorMenu: "readonly",
      fieldGroupInjectionKey: "readonly",
      useFieldGroup: "readonly",
      useFileUpload: "readonly",
      formBusInjectionKey: "readonly",
      formErrorsInjectionKey: "readonly",
      formFieldInjectionKey: "readonly",
      formInputsInjectionKey: "readonly",
      formLoadingInjectionKey: "readonly",
      formOptionsInjectionKey: "readonly",
      formStateInjectionKey: "readonly",
      inputIdInjectionKey: "readonly",
      useFormField: "readonly",
      kbdKeysMap: "readonly",
      useKbd: "readonly",
      localeContextInjectionKey: "readonly",
      useLocale: "readonly",
      useOverlay: "readonly",
      portalTargetInjectionKey: "readonly",
      usePortal: "readonly",
      useResizable: "readonly",
      useScrollspy: "readonly",
      toastMaxInjectionKey: "readonly",
      useToast: "readonly",
      parseMarkdown: "readonly",
      stringifyMarkdown: "readonly",
      unwrapSlot: "readonly",
      useStrapi: "readonly",
      useStrapiAuth: "readonly",
      useStrapiClient: "readonly",
      useStrapiGraphQL: "readonly",
      useStrapiMedia: "readonly",
      useStrapiToken: "readonly",
      useStrapiUrl: "readonly",
      useStrapiUser: "readonly",
      useStrapiVersion: "readonly",
      useFeatureFlagEnabled: "readonly",
      useFeatureFlagPayload: "readonly",
      useFeatureFlagVariantKey: "readonly",
      usePostHog: "readonly",
      clearStudioUserSession: "readonly",
      setStudioUserSession: "readonly",
      definePageMeta: "readonly",
      useGSAP: "readonly",
      APICollectionResponse: "readonly",
      APILocation: "readonly",
      APIProjects: "readonly",
      APISectors: "readonly",
      APIServices: "readonly",
      APITeam: "readonly",
      APITeamMember: "readonly",
      Children: "readonly",
      Content: "readonly",
      ContentProject: "readonly",
      ContentService: "readonly",
      Formats: "readonly",
      Meta: "readonly",
      Pagination: "readonly",
      Photo: "readonly",
      Project: "readonly",
      ProviderMetadata: "readonly",
      Sector: "readonly",
      Service: "readonly",
      Team: "readonly",
      TeamMember: "readonly",
      Link: "readonly",
      catchError: "readonly",
      defineNuxtLink: "readonly",
      clearNuxtData: "readonly",
      refreshNuxtData: "readonly",
      useAsyncData: "readonly",
      useLazyAsyncData: "readonly",
      useNuxtData: "readonly",
      reloadNuxtApp: "readonly",
      defineNuxtComponent: "readonly",
      refreshCookie: "readonly",
      useCookie: "readonly",
      clearError: "readonly",
      createError: "readonly",
      isNuxtError: "readonly",
      showError: "readonly",
      useError: "readonly",
      useFetch: "readonly",
      useLazyFetch: "readonly",
      injectHead: "readonly",
      useHead: "readonly",
      useHeadSafe: "readonly",
      useSeoMeta: "readonly",
      useServerHead: "readonly",
      useServerHeadSafe: "readonly",
      useServerSeoMeta: "readonly",
      useHydration: "readonly",
      defineLazyHydrationComponent: "readonly",
      useLoadingIndicator: "readonly",
      getAppManifest: "readonly",
      getRouteRules: "readonly",
      callOnce: "readonly",
      definePayloadReducer: "readonly",
      definePayloadReviver: "readonly",
      isPrerendered: "readonly",
      loadPayload: "readonly",
      preloadPayload: "readonly",
      prefetchComponents: "readonly",
      preloadComponents: "readonly",
      preloadRouteComponents: "readonly",
      usePreviewMode: "readonly",
      onNuxtReady: "readonly",
      useRouteAnnouncer: "readonly",
      abortNavigation: "readonly",
      addRouteMiddleware: "readonly",
      defineNuxtRouteMiddleware: "readonly",
      navigateTo: "readonly",
      setPageLayout: "readonly",
      useRoute: "readonly",
      useRouter: "readonly",
      useRuntimeHook: "readonly",
      useScript: "readonly",
      useScriptClarity: "readonly",
      useScriptCloudflareWebAnalytics: "readonly",
      useScriptCrisp: "readonly",
      useScriptDatabuddyAnalytics: "readonly",
      useScriptEventPage: "readonly",
      useScriptFathomAnalytics: "readonly",
      useScriptGoogleAdsense: "readonly",
      useScriptGoogleAnalytics: "readonly",
      useScriptGoogleMaps: "readonly",
      useScriptGoogleTagManager: "readonly",
      useScriptHotjar: "readonly",
      useScriptIntercom: "readonly",
      useScriptLemonSqueezy: "readonly",
      useScriptMatomoAnalytics: "readonly",
      useScriptMetaPixel: "readonly",
      useScriptNpm: "readonly",
      useScriptPayPal: "readonly",
      useScriptPlausibleAnalytics: "readonly",
      useScriptRedditPixel: "readonly",
      useScriptRybbitAnalytics: "readonly",
      useScriptSegment: "readonly",
      useScriptSnapchatPixel: "readonly",
      useScriptStripe: "readonly",
      useScriptTriggerConsent: "readonly",
      useScriptTriggerElement: "readonly",
      useScriptUmamiAnalytics: "readonly",
      useScriptVimeoPlayer: "readonly",
      useScriptXPixel: "readonly",
      useScriptYouTubePlayer: "readonly",
      onPrehydrate: "readonly",
      prerenderRoutes: "readonly",
      setResponseStatus: "readonly",
      useRequestEvent: "readonly",
      useRequestFetch: "readonly",
      useRequestHeader: "readonly",
      useRequestHeaders: "readonly",
      useResponseHeader: "readonly",
      clearNuxtState: "readonly",
      useState: "readonly",
      useRequestURL: "readonly",
      updateAppConfig: "readonly",
      useAppConfig: "readonly",
      defineNuxtPlugin: "readonly",
      definePayloadPlugin: "readonly",
      tryUseNuxtApp: "readonly",
      useNuxtApp: "readonly",
      useRuntimeConfig: "readonly",
      appendCorsHeaders: "readonly",
      appendCorsPreflightHeaders: "readonly",
      appendHeader: "readonly",
      appendHeaders: "readonly",
      appendResponseHeader: "readonly",
      appendResponseHeaders: "readonly",
      assertMethod: "readonly",
      callNodeListener: "readonly",
      clearResponseHeaders: "readonly",
      clearSession: "readonly",
      createApp: "readonly",
      createAppEventHandler: "readonly",
      createEvent: "readonly",
      createEventStream: "readonly",
      createRouter: "readonly",
      defaultContentType: "readonly",
      defineEventHandler: "readonly",
      defineLazyEventHandler: "readonly",
      defineNodeListener: "readonly",
      defineNodeMiddleware: "readonly",
      defineRequestMiddleware: "readonly",
      defineResponseMiddleware: "readonly",
      defineWebSocket: "readonly",
      defineWebSocketHandler: "readonly",
      deleteCookie: "readonly",
      dynamicEventHandler: "readonly",
      eventHandler: "readonly",
      EventHandler: "readonly",
      EventHandlerObject: "readonly",
      EventHandlerRequest: "readonly",
      EventHandlerResponse: "readonly",
      fetchWithEvent: "readonly",
      fromNodeMiddleware: "readonly",
      fromPlainHandler: "readonly",
      fromWebHandler: "readonly",
      getCookie: "readonly",
      getHeader: "readonly",
      getHeaders: "readonly",
      getMethod: "readonly",
      getProxyRequestHeaders: "readonly",
      getQuery: "readonly",
      getRequestFingerprint: "readonly",
      getRequestHeader: "readonly",
      getRequestHeaders: "readonly",
      getRequestHost: "readonly",
      getRequestIP: "readonly",
      getRequestPath: "readonly",
      getRequestProtocol: "readonly",
      getRequestURL: "readonly",
      getRequestWebStream: "readonly",
      getResponseHeader: "readonly",
      getResponseHeaders: "readonly",
      getResponseStatus: "readonly",
      getResponseStatusText: "readonly",
      getRouterParam: "readonly",
      getRouterParams: "readonly",
      getSession: "readonly",
      getValidatedQuery: "readonly",
      getValidatedRouterParams: "readonly",
      H3Error: "readonly",
      H3Event: "readonly",
      H3EventContext: "readonly",
      handleCacheHeaders: "readonly",
      handleCors: "readonly",
      isCorsOriginAllowed: "readonly",
      isError: "readonly",
      isEvent: "readonly",
      isEventHandler: "readonly",
      isMethod: "readonly",
      isPreflightRequest: "readonly",
      isStream: "readonly",
      isWebResponse: "readonly",
      lazyEventHandler: "readonly",
      parseCookies: "readonly",
      promisifyNodeListener: "readonly",
      proxyRequest: "readonly",
      readBody: "readonly",
      readFormData: "readonly",
      readMultipartFormData: "readonly",
      readRawBody: "readonly",
      readValidatedBody: "readonly",
      removeResponseHeader: "readonly",
      sanitizeStatusCode: "readonly",
      sanitizeStatusMessage: "readonly",
      sealSession: "readonly",
      send: "readonly",
      sendError: "readonly",
      sendIterable: "readonly",
      sendNoContent: "readonly",
      sendProxy: "readonly",
      sendRedirect: "readonly",
      sendStream: "readonly",
      sendWebResponse: "readonly",
      serveStatic: "readonly",
      setCookie: "readonly",
      setHeader: "readonly",
      setHeaders: "readonly",
      setResponseHeader: "readonly",
      setResponseHeaders: "readonly",
      splitCookiesString: "readonly",
      toEventHandler: "readonly",
      toNodeListener: "readonly",
      toPlainHandler: "readonly",
      toWebHandler: "readonly",
      toWebRequest: "readonly",
      unsealSession: "readonly",
      updateSession: "readonly",
      useBase: "readonly",
      useSession: "readonly",
      writeEarlyHints: "readonly",
      useAnimate: "readonly",
      useAnimationFrame: "readonly",
      useDragControls: "readonly",
      useInView: "readonly",
      useLayoutGroup: "readonly",
      useMotionTemplate: "readonly",
      useMotionValue: "readonly",
      useMotionValueEvent: "readonly",
      useReducedMotion: "readonly",
      useScroll: "readonly",
      useSpring: "readonly",
      useTime: "readonly",
      useTransform: "readonly",
      useVelocity: "readonly",
      useNitroApp: "readonly",
      cachedEventHandler: "readonly",
      cachedFunction: "readonly",
      defineCachedEventHandler: "readonly",
      defineCachedFunction: "readonly",
      useEvent: "readonly",
      defineNitroErrorHandler: "readonly",
      defineRouteMeta: "readonly",
      defineNitroPlugin: "readonly",
      nitroPlugin: "readonly",
      defineRenderHandler: "readonly",
      useStorage: "readonly",
      defineTask: "readonly",
      runTask: "readonly",
      Component: "readonly",
      ComponentPublicInstance: "readonly",
      computed: "readonly",
      ComputedRef: "readonly",
      customRef: "readonly",
      defineAsyncComponent: "readonly",
      defineComponent: "readonly",
      DirectiveBinding: "readonly",
      effect: "readonly",
      effectScope: "readonly",
      ExtractDefaultPropTypes: "readonly",
      ExtractPropTypes: "readonly",
      ExtractPublicPropTypes: "readonly",
      getCurrentInstance: "readonly",
      getCurrentScope: "readonly",
      h: "readonly",
      hasInjectionContext: "readonly",
      inject: "readonly",
      InjectionKey: "readonly",
      isProxy: "readonly",
      isReactive: "readonly",
      isReadonly: "readonly",
      isRef: "readonly",
      isShallow: "readonly",
      markRaw: "readonly",
      MaybeRef: "readonly",
      MaybeRefOrGetter: "readonly",
      nextTick: "readonly",
      onActivated: "readonly",
      onBeforeMount: "readonly",
      onBeforeUnmount: "readonly",
      onBeforeUpdate: "readonly",
      onDeactivated: "readonly",
      onErrorCaptured: "readonly",
      onMounted: "readonly",
      onRenderTracked: "readonly",
      onRenderTriggered: "readonly",
      onScopeDispose: "readonly",
      onServerPrefetch: "readonly",
      onUnmounted: "readonly",
      onUpdated: "readonly",
      onWatcherCleanup: "readonly",
      PropType: "readonly",
      provide: "readonly",
      proxyRefs: "readonly",
      reactive: "readonly",
      readonly: "readonly",
      ref: "readonly",
      Ref: "readonly",
      resolveComponent: "readonly",
      shallowReactive: "readonly",
      shallowReadonly: "readonly",
      shallowRef: "readonly",
      toRaw: "readonly",
      toRef: "readonly",
      toRefs: "readonly",
      toValue: "readonly",
      triggerRef: "readonly",
      unref: "readonly",
      useAttrs: "readonly",
      useCssModule: "readonly",
      useCssVars: "readonly",
      useId: "readonly",
      useModel: "readonly",
      useShadowRoot: "readonly",
      useSlots: "readonly",
      useTemplateRef: "readonly",
      useTransitionState: "readonly",
      VNode: "readonly",
      watch: "readonly",
      watchEffect: "readonly",
      watchPostEffect: "readonly",
      watchSyncEffect: "readonly",
      withCtx: "readonly",
      withDirectives: "readonly",
      withKeys: "readonly",
      withMemo: "readonly",
      withModifiers: "readonly",
      withScopeId: "readonly",
      WritableComputedRef: "readonly",
      isVue2: "readonly",
      isVue3: "readonly",
      onBeforeRouteLeave: "readonly",
      onBeforeRouteUpdate: "readonly",
      useLink: "readonly",
      AudioWorkletGlobalScope: "readonly",
      AudioWorkletProcessor: "readonly",
      currentFrame: "readonly",
      currentTime: "readonly",
      registerProcessor: "readonly",
      sampleRate: "readonly",
      WorkletGlobalScope: "readonly",
      defineEmits: "readonly",
      defineExpose: "readonly",
      defineProps: "readonly",
    },
    ignorePatterns: [
      "**/.output",
      "**/.data",
      "**/.nuxt",
      "**/.nitro",
      "**/.cache",
      "**/dist",
      "**/node_modules",
      "**/logs",
      "**/*.log",
      "**/.DS_Store",
      "**/.fleet",
      "**/.idea",
      "**/AGENTS.md",
      "**/context.md",
      "**/.env",
      "**/.env.*",
      "!**/.env.example",
      "**/.vercel",
      "**/.worktrees/",
      "**/package-lock.json",
      "**/yarn.lock",
      "**/pnpm-lock.yaml",
      "**/bun.lockb",
      "**/output",
      "**/coverage",
      "**/temp",
      "**/.temp",
      "**/tmp",
      "**/.tmp",
      "**/.history",
      "**/.vitepress/cache",
      "**/.next",
      "**/.svelte-kit",
      "**/.changeset",
      "**/.vite-inspect",
      "**/.yarn",
      "**/vite.config.*.timestamp-*",
      "**/CHANGELOG*.md",
      "**/*.min.*",
      "**/LICENSE*",
      "**/__snapshots__",
      "**/auto-import?(s).d.ts",
      "**/components.d.ts",
      ".pnpm-store/**",
      "**/migrations/*",
      "GEMINI.md",
      "PLAN.md",
      "public/maplibre-gl.css",
      "CLAUDE.md",
    ],
    rules: {
      "@nuxt/prefer-import-meta": "error",
      "accessor-pairs": [
        "error",
        {
          enforceForClassMembers: true,
          setWithoutGet: true,
        },
      ],
      "array-callback-return": "error",
      "block-scoped-var": "error",
      "constructor-super": "error",
      "default-case-last": "error",
      "@typescript-eslint/dot-notation": [
        "error",
        {
          allowKeywords: true,
        },
      ],
      eqeqeq: ["error", "smart"],
      "new-cap": [
        "error",
        {
          capIsNew: false,
          newIsCap: true,
          properties: true,
        },
      ],
      "no-alert": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "always"],
      "no-console": [
        "error",
        {
          allow: ["warn", "error"],
        },
      ],
      "no-const-assign": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-class-members": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": [
        "error",
        {
          allowEmptyCatch: true,
        },
      ],
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-labels": [
        "error",
        {
          allowLoop: false,
          allowSwitch: false,
        },
      ],
      "no-lone-blocks": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-multi-str": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-wrappers": "error",
      "no-obj-calls": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-regex-spaces": "error",
      "no-restricted-globals": [
        "error",
        {
          message: "Use `globalThis` instead.",
          name: "global",
        },
        {
          message: "Use `globalThis` instead.",
          name: "self",
        },
      ],
      "no-self-assign": [
        "error",
        {
          props: true,
        },
      ],
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "error",
      "no-this-before-super": "error",
      "no-throw-literal": "error",
      "no-undef": "error",
      "no-unexpected-multiline": "error",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": [
        "error",
        {
          defaultAssignment: false,
        },
      ],
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      "no-unused-vars": [
        "error",
        {
          args: "none",
          caughtErrors: "none",
          ignoreRestSiblings: true,
          vars: "all",
        },
      ],
      "no-use-before-define": [
        "error",
        {
          classes: false,
          functions: false,
          variables: true,
        },
      ],
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-constructor": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-with": "error",
      "prefer-const": [
        "error",
        {
          destructuring: "all",
          ignoreReadBeforeAssign: true,
        },
      ],
      "prefer-exponentiation-operator": "error",
      "prefer-promise-reject-errors": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      "symbol-description": "error",
      "unicode-bom": ["error", "never"],
      "unused-imports/no-unused-imports": "off",
      "unused-imports/no-unused-vars": [
        "off",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          ignoreRestSiblings: true,
          vars: "all",
          varsIgnorePattern: "^_",
        },
      ],
      "use-isnan": [
        "error",
        {
          enforceForIndexOf: true,
          enforceForSwitchCase: true,
        },
      ],
      "valid-typeof": [
        "error",
        {
          requireStringLiterals: true,
        },
      ],
      "vars-on-top": "error",
      yoda: ["error", "never"],
      "eslint-comments/no-aggregating-enable": "error",
      "eslint-comments/no-duplicate-disable": "error",
      "eslint-comments/no-unlimited-disable": "error",
      "eslint-comments/no-unused-enable": "error",
      "node/handle-callback-err": ["error", "^(err|error)$"],
      "node/no-exports-assign": "error",
      "node/no-new-require": "error",
      "node/no-path-concat": "error",
      "jsdoc/check-access": "warn",
      "jsdoc/empty-tags": "warn",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-returns-description": "warn",
      "antfu/import-dedupe": "error",
      "antfu/no-import-dist": "error",
      "antfu/no-import-node-modules-by-path": "error",
      "import/consistent-type-specifier-style": ["error", "prefer-top-level"],
      "import/first": "error",
      "import/no-duplicates": "error",
      "import/no-mutable-exports": "error",
      "import/no-named-default": "error",
      "command/command": "error",
      "perfectionist/sort-exports": [
        "error",
        {
          order: "asc",
          type: "natural",
        },
      ],
      "perfectionist/sort-named-exports": [
        "error",
        {
          order: "asc",
          type: "natural",
        },
      ],
      "perfectionist/sort-named-imports": [
        "error",
        {
          order: "asc",
          type: "natural",
        },
      ],
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-instanceof-builtins": "error",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/number-literal-case": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-includes": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/throw-new-error": "error",
      "@stylistic/array-bracket-spacing": ["error", "never"],
      "@stylistic/arrow-parens": [
        "error",
        "as-needed",
        {
          requireForBlockBody: true,
        },
      ],
      "@stylistic/arrow-spacing": [
        "error",
        {
          after: true,
          before: true,
        },
      ],
      "@stylistic/block-spacing": ["error", "always"],
      "@stylistic/brace-style": [
        "error",
        "stroustrup",
        {
          allowSingleLine: true,
        },
      ],
      "@stylistic/comma-dangle": ["error", "always-multiline"],
      "@stylistic/comma-spacing": [
        "error",
        {
          after: true,
          before: false,
        },
      ],
      "@stylistic/comma-style": ["error", "last"],
      "@stylistic/computed-property-spacing": [
        "error",
        "never",
        {
          enforceForClassMembers: true,
        },
      ],
      "@stylistic/dot-location": ["error", "property"],
      "@stylistic/eol-last": "error",
      "@stylistic/generator-star-spacing": [
        "error",
        {
          after: true,
          before: false,
        },
      ],
      "@stylistic/indent": [
        "error",
        2,
        {
          ArrayExpression: 1,
          CallExpression: {
            arguments: 1,
          },
          flatTernaryExpressions: false,
          FunctionDeclaration: {
            body: 1,
            parameters: 1,
            returnType: 1,
          },
          FunctionExpression: {
            body: 1,
            parameters: 1,
            returnType: 1,
          },
          ignoreComments: false,
          ignoredNodes: ["TSUnionType", "TSIntersectionType"],
          ImportDeclaration: 1,
          MemberExpression: 1,
          ObjectExpression: 1,
          offsetTernaryExpressions: true,
          outerIIFEBody: 1,
          SwitchCase: 1,
          tabLength: 2,
          VariableDeclarator: 1,
        },
      ],
      "@stylistic/indent-binary-ops": ["error", 2],
      "@stylistic/key-spacing": [
        "error",
        {
          afterColon: true,
          beforeColon: false,
        },
      ],
      "@stylistic/keyword-spacing": [
        "error",
        {
          after: true,
          before: true,
        },
      ],
      "@stylistic/lines-between-class-members": [
        "error",
        "always",
        {
          exceptAfterSingleLine: true,
        },
      ],
      "@stylistic/max-statements-per-line": [
        "error",
        {
          max: 1,
        },
      ],
      "@stylistic/member-delimiter-style": [
        "error",
        {
          multiline: {
            delimiter: "semi",
            requireLast: true,
          },
          multilineDetection: "brackets",
          overrides: {
            interface: {
              multiline: {
                delimiter: "semi",
                requireLast: true,
              },
            },
          },
          singleline: {
            delimiter: "semi",
          },
        },
      ],
      "@stylistic/multiline-ternary": ["error", "always-multiline"],
      "@stylistic/new-parens": "error",
      "@stylistic/no-extra-parens": ["error", "functions"],
      "@stylistic/no-floating-decimal": "error",
      "@stylistic/no-mixed-operators": [
        "error",
        {
          allowSamePrecedence: true,
          groups: [
            ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
            ["&&", "||"],
            ["in", "instanceof"],
          ],
        },
      ],
      "@stylistic/no-mixed-spaces-and-tabs": "error",
      "@stylistic/no-multi-spaces": "error",
      "@stylistic/no-multiple-empty-lines": [
        "error",
        {
          max: 1,
          maxBOF: 0,
          maxEOF: 0,
        },
      ],
      "@stylistic/no-tabs": "error",
      "@stylistic/no-trailing-spaces": "error",
      "@stylistic/no-whitespace-before-property": "error",
      "@stylistic/object-curly-spacing": ["error", "always"],
      "@stylistic/operator-linebreak": ["error", "before"],
      "@stylistic/padded-blocks": [
        "error",
        {
          blocks: "never",
          classes: "never",
          switches: "never",
        },
      ],
      "@stylistic/quote-props": ["error", "consistent-as-needed"],
      "@stylistic/quotes": [
        "error",
        "single",
        {
          allowTemplateLiterals: "always",
          avoidEscape: false,
        },
      ],
      "@stylistic/rest-spread-spacing": ["error", "never"],
      "@stylistic/semi": ["error", "always"],
      "@stylistic/semi-spacing": [
        "error",
        {
          after: true,
          before: false,
        },
      ],
      "@stylistic/space-before-blocks": ["error", "always"],
      "@stylistic/space-before-function-paren": [
        "error",
        {
          anonymous: "always",
          asyncArrow: "always",
          named: "never",
        },
      ],
      "@stylistic/space-in-parens": ["error", "never"],
      "@stylistic/space-infix-ops": "error",
      "@stylistic/space-unary-ops": [
        "error",
        {
          nonwords: false,
          words: true,
        },
      ],
      "@stylistic/spaced-comment": [
        "error",
        "always",
        {
          block: {
            balanced: true,
            exceptions: ["*"],
            markers: ["!"],
          },
          line: {
            exceptions: ["/", "#"],
            markers: ["/"],
          },
        },
      ],
      "@stylistic/template-curly-spacing": "error",
      "@stylistic/template-tag-spacing": ["error", "never"],
      "@stylistic/type-annotation-spacing": ["error", {}],
      "@stylistic/type-generic-spacing": "error",
      "@stylistic/type-named-tuple-spacing": "error",
      "@stylistic/wrap-iife": [
        "error",
        "any",
        {
          functionPrototypeMethods: true,
        },
      ],
      "@stylistic/yield-star-spacing": [
        "error",
        {
          after: true,
          before: false,
        },
      ],
      "@stylistic/jsx-closing-bracket-location": "error",
      "@stylistic/jsx-closing-tag-location": "error",
      "@stylistic/jsx-curly-brace-presence": [
        "error",
        {
          propElementValues: "always",
        },
      ],
      "@stylistic/jsx-curly-newline": "error",
      "@stylistic/jsx-curly-spacing": ["error", "never"],
      "@stylistic/jsx-equals-spacing": "error",
      "@stylistic/jsx-first-prop-new-line": "error",
      "@stylistic/jsx-function-call-newline": ["error", "multiline"],
      "@stylistic/jsx-indent-props": ["error", 2],
      "@stylistic/jsx-max-props-per-line": [
        "error",
        {
          maximum: 1,
          when: "multiline",
        },
      ],
      "@stylistic/jsx-one-expression-per-line": [
        "error",
        {
          allow: "single-child",
        },
      ],
      "@stylistic/jsx-quotes": "error",
      "@stylistic/jsx-tag-spacing": [
        "error",
        {
          afterOpening: "never",
          beforeClosing: "never",
          beforeSelfClosing: "always",
          closingSlash: "never",
        },
      ],
      "@stylistic/jsx-wrap-multilines": [
        "error",
        {
          arrow: "parens-new-line",
          assignment: "parens-new-line",
          condition: "parens-new-line",
          declaration: "parens-new-line",
          logical: "parens-new-line",
          prop: "parens-new-line",
          propertyValue: "parens-new-line",
          return: "parens-new-line",
        },
      ],
      "antfu/consistent-chaining": "error",
      "antfu/consistent-list-newline": "error",
      "antfu/curly": "error",
      "antfu/if-newline": "error",
      "antfu/top-level-function": "error",
      "regexp/confusing-quantifier": "warn",
      "regexp/control-character-escape": "error",
      "regexp/match-any": "error",
      "regexp/negation": "error",
      "regexp/no-contradiction-with-assertion": "error",
      "regexp/no-dupe-characters-character-class": "error",
      "regexp/no-dupe-disjunctions": "error",
      "regexp/no-empty-alternative": "warn",
      "regexp/no-empty-capturing-group": "error",
      "regexp/no-empty-character-class": "error",
      "regexp/no-empty-group": "error",
      "regexp/no-empty-lookarounds-assertion": "error",
      "regexp/no-empty-string-literal": "error",
      "regexp/no-escape-backspace": "error",
      "regexp/no-extra-lookaround-assertions": "error",
      "regexp/no-invalid-regexp": "error",
      "regexp/no-invisible-character": "error",
      "regexp/no-lazy-ends": "warn",
      "regexp/no-legacy-features": "error",
      "regexp/no-misleading-capturing-group": "error",
      "regexp/no-misleading-unicode-character": "error",
      "regexp/no-missing-g-flag": "error",
      "regexp/no-non-standard-flag": "error",
      "regexp/no-obscure-range": "error",
      "regexp/no-optional-assertion": "error",
      "regexp/no-potentially-useless-backreference": "warn",
      "regexp/no-super-linear-backtracking": "error",
      "regexp/no-trivially-nested-assertion": "error",
      "regexp/no-trivially-nested-quantifier": "error",
      "regexp/no-unused-capturing-group": "error",
      "regexp/no-useless-assertions": "error",
      "regexp/no-useless-backreference": "error",
      "regexp/no-useless-character-class": "error",
      "regexp/no-useless-dollar-replacements": "error",
      "regexp/no-useless-escape": "error",
      "regexp/no-useless-flag": "warn",
      "regexp/no-useless-lazy": "error",
      "regexp/no-useless-non-capturing-group": "error",
      "regexp/no-useless-quantifier": "error",
      "regexp/no-useless-range": "error",
      "regexp/no-useless-set-operand": "error",
      "regexp/no-useless-string-literal": "error",
      "regexp/no-useless-two-nums-quantifier": "error",
      "regexp/no-zero-quantifier": "error",
      "regexp/optimal-lookaround-quantifier": "warn",
      "regexp/optimal-quantifier-concatenation": "error",
      "regexp/prefer-character-class": "error",
      "regexp/prefer-d": "error",
      "regexp/prefer-plus-quantifier": "error",
      "regexp/prefer-predefined-assertion": "error",
      "regexp/prefer-question-quantifier": "error",
      "regexp/prefer-range": "error",
      "regexp/prefer-set-operation": "error",
      "regexp/prefer-star-quantifier": "error",
      "regexp/prefer-unicode-codepoint-escapes": "error",
      "regexp/prefer-w": "error",
      "regexp/simplify-set-operations": "error",
      "regexp/sort-flags": "error",
      "regexp/strict": "error",
      "regexp/use-ignore-case": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "unicorn/filename-case": [
        "error",
        {
          case: "kebabCase",
          ignore: ["README.md"],
        },
      ],
    },
    overrides: [
      {
        files: ["**/*.?([cm])ts", "**/*.?([cm])tsx", "**/*.vue"],
        rules: {
          "constructor-super": "off",
          "getter-return": "off",
          "no-class-assign": "off",
          "no-const-assign": "off",
          "no-dupe-keys": "off",
          "no-func-assign": "off",
          "no-import-assign": "off",
          "no-new-native-nonconstructor": "off",
          "no-obj-calls": "off",
          "no-redeclare": [
            "error",
            {
              builtinGlobals: false,
            },
          ],
          "no-setter-return": "off",
          "no-this-before-super": "off",
          "no-undef": "off",
          "no-unreachable": "off",
          "no-unsafe-negation": "off",
          "no-with": "off",
          "prefer-const": "error",
          "@typescript-eslint/ban-ts-comment": [
            "error",
            {
              "ts-expect-error": "allow-with-description",
            },
          ],
          "@typescript-eslint/no-duplicate-enum-values": "error",
          "@typescript-eslint/no-dynamic-delete": "off",
          "@typescript-eslint/no-empty-object-type": [
            "error",
            {
              allowInterfaces: "always",
            },
          ],
          "@typescript-eslint/no-explicit-any": "off",
          "@typescript-eslint/no-extra-non-null-assertion": "error",
          "@typescript-eslint/no-extraneous-class": "off",
          "@typescript-eslint/no-invalid-void-type": "off",
          "@typescript-eslint/no-misused-new": "error",
          "@typescript-eslint/no-namespace": "error",
          "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
          "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
          "@typescript-eslint/no-non-null-assertion": "off",
          "@typescript-eslint/no-require-imports": "error",
          "@typescript-eslint/no-this-alias": "error",
          "@typescript-eslint/no-unnecessary-type-constraint": "error",
          "@typescript-eslint/no-unsafe-declaration-merging": "error",
          "@typescript-eslint/no-unsafe-function-type": "error",
          "no-unused-expressions": [
            "error",
            {
              allowShortCircuit: true,
              allowTaggedTemplates: true,
              allowTernary: true,
            },
          ],
          "no-unused-vars": "off",
          "no-useless-constructor": "off",
          "@typescript-eslint/no-wrapper-object-types": "error",
          "@typescript-eslint/prefer-as-const": "error",
          "@typescript-eslint/prefer-literal-enum-member": "error",
          "@typescript-eslint/prefer-namespace-keyword": "error",
          "@typescript-eslint/triple-slash-reference": "off",
          "@typescript-eslint/unified-signatures": "off",
          "no-use-before-define": [
            "error",
            {
              classes: false,
              functions: false,
              variables: true,
            },
          ],
          "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
          "@typescript-eslint/consistent-type-imports": [
            "error",
            {
              disallowTypeAnnotations: false,
              fixStyle: "separate-type-imports",
              prefer: "type-imports",
            },
          ],
          "@typescript-eslint/no-import-type-side-effects": "error",
        },
      },
      {
        files: [
          "**/__tests__/**/*.?([cm])[jt]s?(x)",
          "**/*.spec.?([cm])[jt]s?(x)",
          "**/*.test.?([cm])[jt]s?(x)",
          "**/*.bench.?([cm])[jt]s?(x)",
          "**/*.benchmark.?([cm])[jt]s?(x)",
        ],
        rules: {
          "vitest/consistent-test-it": [
            "error",
            {
              fn: "it",
              withinDescribe: "it",
            },
          ],
          "vitest/no-identical-title": "error",
          "vitest/no-import-node-test": "error",
          "vitest/prefer-hooks-in-order": "error",
          "vitest/prefer-lowercase-title": "error",
          "antfu/no-top-level-await": "off",
          "no-unused-expressions": "off",
          "@typescript-eslint/explicit-function-return-type": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
        plugins: ["vitest"],
      },
      {
        files: ["**/*.vue"],
        rules: {
          "vue/no-arrow-functions-in-watch": "error",
          "vue/no-deprecated-destroyed-lifecycle": "error",
          "vue/no-export-in-script-setup": "error",
          "vue/no-lifecycle-after-await": "error",
          "vue/prefer-import-from-vue": "error",
          "vue/valid-define-emits": "error",
          "vue/valid-define-props": "error",
          "vue/no-multiple-slot-args": "warn",
          "vue/no-required-prop-with-default": "warn",
          "antfu/no-top-level-await": "off",
          "@typescript-eslint/explicit-function-return-type": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
        plugins: ["vue"],
      },
      {
        files: ["**/*.json", "**/*.json5", "**/*.jsonc"],
        rules: {
          "jsonc/no-bigint-literals": "error",
          "jsonc/no-binary-expression": "error",
          "jsonc/no-binary-numeric-literals": "error",
          "jsonc/no-dupe-keys": "error",
          "jsonc/no-escape-sequence-in-identifier": "error",
          "jsonc/no-floating-decimal": "error",
          "jsonc/no-hexadecimal-numeric-literals": "error",
          "jsonc/no-infinity": "error",
          "jsonc/no-multi-str": "error",
          "jsonc/no-nan": "error",
          "jsonc/no-number-props": "error",
          "jsonc/no-numeric-separators": "error",
          "jsonc/no-octal": "error",
          "jsonc/no-octal-escape": "error",
          "jsonc/no-octal-numeric-literals": "error",
          "jsonc/no-parenthesized": "error",
          "jsonc/no-plus-sign": "error",
          "jsonc/no-regexp-literals": "error",
          "jsonc/no-sparse-arrays": "error",
          "jsonc/no-template-literals": "error",
          "jsonc/no-undefined-value": "error",
          "jsonc/no-unicode-codepoint-escapes": "error",
          "jsonc/no-useless-escape": "error",
          "jsonc/space-unary-ops": "error",
          "jsonc/valid-json-number": "error",
          "jsonc/vue-custom-block/no-parsing-error": "error",
          "jsonc/array-bracket-spacing": ["error", "never"],
          "jsonc/comma-dangle": ["error", "never"],
          "jsonc/comma-style": ["error", "last"],
          "jsonc/indent": ["error", 2],
          "jsonc/key-spacing": [
            "error",
            {
              afterColon: true,
              beforeColon: false,
            },
          ],
          "jsonc/object-curly-newline": [
            "error",
            {
              consistent: true,
              multiline: true,
            },
          ],
          "jsonc/object-curly-spacing": ["error", "always"],
          "jsonc/object-property-newline": [
            "error",
            {
              allowAllPropertiesOnSameLine: true,
            },
          ],
          "jsonc/quote-props": "error",
          "jsonc/quotes": "error",
        },
        jsPlugins: ["eslint-plugin-jsonc"],
      },
      {
        files: ["**/package.json"],
        rules: {
          "jsonc/sort-array-values": [
            "error",
            {
              order: {
                type: "asc",
              },
              pathPattern: "^files$",
            },
          ],
          "jsonc/sort-keys": [
            "error",
            {
              order: [
                "publisher",
                "name",
                "displayName",
                "type",
                "version",
                "private",
                "packageManager",
                "description",
                "author",
                "contributors",
                "license",
                "funding",
                "homepage",
                "repository",
                "bugs",
                "keywords",
                "categories",
                "sideEffects",
                "imports",
                "exports",
                "main",
                "module",
                "unpkg",
                "jsdelivr",
                "types",
                "typesVersions",
                "bin",
                "icon",
                "files",
                "engines",
                "activationEvents",
                "contributes",
                "scripts",
                "peerDependencies",
                "peerDependenciesMeta",
                "dependencies",
                "optionalDependencies",
                "devDependencies",
                "pnpm",
                "overrides",
                "resolutions",
                "husky",
                "simple-git-hooks",
                "lint-staged",
                "eslintConfig",
              ],
              pathPattern: "^$",
            },
            {
              order: {
                type: "asc",
              },
              pathPattern: "^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$",
            },
            {
              order: {
                type: "asc",
              },
              pathPattern: "^(?:resolutions|overrides|pnpm.overrides)$",
            },
            {
              order: {
                type: "asc",
              },
              pathPattern: "^workspaces\\.catalog$",
            },
            {
              order: {
                type: "asc",
              },
              pathPattern: "^workspaces\\.catalogs\\.[^.]+$",
            },
            {
              order: ["types", "import", "require", "default"],
              pathPattern: "^exports.*$",
            },
            {
              order: [
                "pre-commit",
                "prepare-commit-msg",
                "commit-msg",
                "post-commit",
                "pre-rebase",
                "post-rewrite",
                "post-checkout",
                "post-merge",
                "pre-push",
                "pre-auto-gc",
              ],
              pathPattern: "^(?:gitHooks|husky|simple-git-hooks)$",
            },
          ],
        },
        jsPlugins: ["eslint-plugin-jsonc"],
      },
      {
        files: ["**/[jt]sconfig.json", "**/[jt]sconfig.*.json"],
        rules: {
          "jsonc/sort-keys": [
            "error",
            {
              order: ["extends", "compilerOptions", "references", "files", "include", "exclude"],
              pathPattern: "^$",
            },
            {
              order: [
                "incremental",
                "composite",
                "tsBuildInfoFile",
                "disableSourceOfProjectReferenceRedirect",
                "disableSolutionSearching",
                "disableReferencedProjectLoad",
                "target",
                "jsx",
                "jsxFactory",
                "jsxFragmentFactory",
                "jsxImportSource",
                "lib",
                "moduleDetection",
                "noLib",
                "reactNamespace",
                "useDefineForClassFields",
                "emitDecoratorMetadata",
                "experimentalDecorators",
                "libReplacement",
                "baseUrl",
                "rootDir",
                "rootDirs",
                "customConditions",
                "module",
                "moduleResolution",
                "moduleSuffixes",
                "noResolve",
                "paths",
                "resolveJsonModule",
                "resolvePackageJsonExports",
                "resolvePackageJsonImports",
                "typeRoots",
                "types",
                "allowArbitraryExtensions",
                "allowImportingTsExtensions",
                "allowUmdGlobalAccess",
                "allowJs",
                "checkJs",
                "maxNodeModuleJsDepth",
                "strict",
                "strictBindCallApply",
                "strictFunctionTypes",
                "strictNullChecks",
                "strictPropertyInitialization",
                "allowUnreachableCode",
                "allowUnusedLabels",
                "alwaysStrict",
                "exactOptionalPropertyTypes",
                "noFallthroughCasesInSwitch",
                "noImplicitAny",
                "noImplicitOverride",
                "noImplicitReturns",
                "noImplicitThis",
                "noPropertyAccessFromIndexSignature",
                "noUncheckedIndexedAccess",
                "noUnusedLocals",
                "noUnusedParameters",
                "useUnknownInCatchVariables",
                "declaration",
                "declarationDir",
                "declarationMap",
                "downlevelIteration",
                "emitBOM",
                "emitDeclarationOnly",
                "importHelpers",
                "importsNotUsedAsValues",
                "inlineSourceMap",
                "inlineSources",
                "mapRoot",
                "newLine",
                "noEmit",
                "noEmitHelpers",
                "noEmitOnError",
                "outDir",
                "outFile",
                "preserveConstEnums",
                "preserveValueImports",
                "removeComments",
                "sourceMap",
                "sourceRoot",
                "stripInternal",
                "allowSyntheticDefaultImports",
                "esModuleInterop",
                "forceConsistentCasingInFileNames",
                "isolatedDeclarations",
                "isolatedModules",
                "preserveSymlinks",
                "verbatimModuleSyntax",
                "erasableSyntaxOnly",
                "skipDefaultLibCheck",
                "skipLibCheck",
              ],
              pathPattern: "^compilerOptions$",
            },
          ],
        },
        jsPlugins: ["eslint-plugin-jsonc"],
      },
      {
        files: ["**/*.y?(a)ml"],
        rules: {
          "@stylistic/spaced-comment": "off",
          "yml/block-mapping": "error",
          "yml/block-sequence": "error",
          "yml/no-empty-key": "error",
          "yml/no-empty-sequence-entry": "error",
          "yml/no-irregular-whitespace": "error",
          "yml/plain-scalar": "error",
          "yml/vue-custom-block/no-parsing-error": "error",
          "yml/block-mapping-question-indicator-newline": "error",
          "yml/block-sequence-hyphen-indicator-newline": "error",
          "yml/flow-mapping-curly-newline": "error",
          "yml/flow-mapping-curly-spacing": "error",
          "yml/flow-sequence-bracket-newline": "error",
          "yml/flow-sequence-bracket-spacing": "error",
          "yml/indent": ["error", 2],
          "yml/key-spacing": "error",
          "yml/no-tab-indent": "error",
          "yml/quotes": [
            "error",
            {
              avoidEscape: true,
              prefer: "single",
            },
          ],
          "yml/spaced-comment": "error",
        },
        jsPlugins: ["@stylistic/eslint-plugin", "eslint-plugin-yml"],
      },
      {
        files: ["pnpm-workspace.yaml"],
        rules: {
          "yml/sort-keys": [
            "error",
            {
              order: [
                "packages",
                "overrides",
                "patchedDependencies",
                "hoistPattern",
                "catalog",
                "catalogs",
                "allowedDeprecatedVersions",
                "allowNonAppliedPatches",
                "configDependencies",
                "ignoredBuiltDependencies",
                "ignoredOptionalDependencies",
                "neverBuiltDependencies",
                "onlyBuiltDependencies",
                "onlyBuiltDependenciesFile",
                "packageExtensions",
                "peerDependencyRules",
                "supportedArchitectures",
              ],
              pathPattern: "^$",
            },
            {
              order: {
                type: "asc",
              },
              pathPattern: ".*",
            },
          ],
        },
        jsPlugins: ["eslint-plugin-yml"],
      },
      {
        files: ["**/*.toml"],
        rules: {
          "@stylistic/spaced-comment": "off",
          "toml/comma-style": "error",
          "toml/keys-order": "error",
          "toml/no-space-dots": "error",
          "toml/no-unreadable-number-separator": "error",
          "toml/precision-of-fractional-seconds": "error",
          "toml/precision-of-integer": "error",
          "toml/tables-order": "error",
          "toml/vue-custom-block/no-parsing-error": "error",
          "toml/array-bracket-newline": "error",
          "toml/array-bracket-spacing": "error",
          "toml/array-element-newline": "error",
          "toml/indent": ["error", 2],
          "toml/inline-table-curly-spacing": "error",
          "toml/key-spacing": "error",
          "toml/padding-line-between-pairs": "error",
          "toml/padding-line-between-tables": "error",
          "toml/quoted-keys": "error",
          "toml/spaced-comment": "error",
          "toml/table-bracket-spacing": "error",
        },
        jsPlugins: ["@stylistic/eslint-plugin", "eslint-plugin-toml"],
      },
      {
        files: ["**/*.md/**/*.?([cm])[jt]s?(x)", "**/*.md/**/*.vue"],
        rules: {
          "antfu/no-top-level-await": "off",
          "no-alert": "off",
          "no-console": "off",
          "no-labels": "off",
          "no-lone-blocks": "off",
          "no-undef": "off",
          "no-unused-expressions": "off",
          "no-unused-labels": "off",
          "no-unused-vars": "off",
          "@stylistic/comma-dangle": "off",
          "@stylistic/eol-last": "off",
          "@stylistic/padding-line-between-statements": "off",
          "@typescript-eslint/consistent-type-imports": "off",
          "@typescript-eslint/explicit-function-return-type": "off",
          "@typescript-eslint/no-namespace": "off",
          "@typescript-eslint/no-require-imports": "off",
          "unicode-bom": "off",
          "unused-imports/no-unused-imports": "off",
          "unused-imports/no-unused-vars": "off",
          "no-redeclare": "off",
          "no-use-before-define": "off",
        },
        jsPlugins: [
          "eslint-plugin-antfu",
          "@stylistic/eslint-plugin",
          "eslint-plugin-unused-imports",
        ],
      },
      {
        files: ["**/*.css", "**/*.{p,post}css"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "css",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.scss"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "scss",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.less"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "less",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.htm?(l)"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "html",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.md"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              embeddedLanguageFormatting: "off",
              parser: "markdown",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/*.{g,graph}ql"],
        rules: {
          "format/prettier": [
            "error",
            {
              endOfLine: "auto",
              printWidth: 120,
              semi: true,
              singleQuote: true,
              tabWidth: 2,
              trailingComma: "all",
              useTabs: false,
              parser: "graphql",
              plugins: [],
            },
          ],
        },
        jsPlugins: ["eslint-plugin-format"],
      },
      {
        files: ["**/scripts/**/*.?([cm])[jt]s?(x)"],
        rules: {
          "antfu/no-top-level-await": "off",
          "no-console": "off",
          "@typescript-eslint/explicit-function-return-type": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
      },
      {
        files: ["**/cli/**/*.?([cm])[jt]s?(x)", "**/cli.?([cm])[jt]s?(x)"],
        rules: {
          "antfu/no-top-level-await": "off",
          "no-console": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
      },
      {
        files: ["**/bin/**/*", "**/bin.?([cm])[jt]s?(x)"],
        rules: {
          "antfu/no-import-dist": "off",
          "antfu/no-import-node-modules-by-path": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
      },
      {
        files: ["**/*.d.?([cm])ts"],
        rules: {
          "eslint-comments/no-unlimited-disable": "off",
          "unused-imports/no-unused-vars": "off",
        },
        jsPlugins: ["eslint-plugin-eslint-comments", "eslint-plugin-unused-imports"],
      },
      {
        files: ["**/*.js", "**/*.cjs"],
        rules: {
          "@typescript-eslint/no-require-imports": "off",
        },
      },
      {
        files: ["**/*.config.?([cm])[jt]s?(x)", "**/*.config.*.?([cm])[jt]s?(x)"],
        rules: {
          "antfu/no-top-level-await": "off",
          "no-console": "off",
          "@typescript-eslint/explicit-function-return-type": "off",
        },
        jsPlugins: ["eslint-plugin-antfu"],
      },
    ],
  },
});
