/**
 * AUTO-CAPTURED content snapshot from https://envision-cs.com (de-CMS migration).
 * This is now the site's source of truth for content — edit these files to change the site.
 * Regenerate with scratchpad/snapshot.mjs if ever reconnected to a CMS.
 */
export default [
  {
    "id": 27,
    "documentId": "gi7m2l7w99acbaa2i0j6w4cn",
    "name": "K-12 Education",
    "slug": "k-12-education",
    "createdAt": "2026-02-20T01:03:04.328Z",
    "updatedAt": "2026-06-05T03:40:30.866Z",
    "publishedAt": "2026-06-05T03:40:30.926Z",
    "description": "Active learning environments built around students, schedules, and community trust",
    "image": {
      "id": 173,
      "documentId": "5db62343a64345d1994d5858",
      "name": "20230801_072634.webp",
      "alternativeText": null,
      "caption": null,
      "width": 3000,
      "height": 4000,
      "formats": {},
      "hash": "20230801_072634_6997b239",
      "ext": ".webp",
      "mime": "image/webp",
      "size": 7864.34,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/20230801_072634.webp",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/20230801_072634.webp?updatedAt=1771549242818",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "6997b2395c7cd75eb8f61b7e"
      },
      "createdAt": "2026-02-20T01:00:59.832Z",
      "updatedAt": "2026-02-20T01:00:59.832Z",
      "publishedAt": "2026-02-20T01:00:59.832Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 146,
        "documentId": "bu7p7adakmgctqop2utydkoa",
        "title": "Hillsborough County Public Schools Aquilla J. Morgan High School",
        "slug": "hillsborough-county-public-schools-aquilla-j-morgan-high-school-1",
        "completed": "2025-07-01",
        "location": "Tampa, FL",
        "area": "359,000 SF",
        "createdAt": "2026-02-20T00:45:44.473Z",
        "updatedAt": "2026-06-05T14:10:55.251Z",
        "publishedAt": "2026-06-05T14:10:55.343Z",
        "description": "With a value of $176 million, size of 359,000 SF, and capacity of 3,500 students, Aquilla J. Morgan High School now takes the title of the largest high school in Hillsborough County. This grand new-build high school’s academic spaces include modern, spacious classrooms, a culinary lab, automotive lab, cosmetology lab, digital art studio, and game design space. Activity spaces include a two-story media center, two-story gym with a two-lane indoor walking track, football field, theater, and auditorium with an orchestra pit. \n\nThe high school was built not only to relieve enrollment at Riverview, Bloomingdale, Sumner, and Lennard high schools, but to also serve as a community shelter during emergencies. \n",
        "beck": true
      },
      {
        "id": 207,
        "documentId": "m23eg3juqe7oia137360x8tw",
        "title": "Hillsborough County Public Schools Gary Adult Referendum (7 Year) HVAC Repair",
        "slug": "hillsborough-county-public-schools-gary-adult-referendum-7-year-hvac-repair",
        "completed": "2025-07-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-20T00:51:49.082Z",
        "updatedAt": "2026-06-06T22:02:23.769Z",
        "publishedAt": "2026-06-06T22:02:23.827Z",
        "description": "To perform the HVAC repair and replacement project at Gary Adult School, our team examined the existing system with a detailed site assessment and developed appropriate solutions. We collaborated closely with stakeholders to ensure all project requirements were met, prepared detailed design and engineering plans, and procured the required materials and equipment. During the construction phase, our team completed the HVAC repair and replacement, adhering to the agreed timeline and industry standards.\n  \nWhen unanticipated equipment and shipping delays arose, our team responded with agility by keeping Hillsborough County Public Schools informed, coordinating with vendors on revised delivery dates, and resequencing work to keep the project moving. This proacitve coordination allowed our team to successfully complete this project within the summer construction window, finishing the project before the start of the new school year. ",
        "beck": null
      },
      {
        "id": 206,
        "documentId": "rrjirzlp98xy1r9lwkfjb0sg",
        "title": "Hillsborough County Public Schools Kitchen Mechanical Replacements",
        "slug": "hillsborough-county-public-schools-kitchen-mechanical-replacements",
        "completed": "2025-07-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-20T00:49:12.793Z",
        "updatedAt": "2026-06-06T22:01:13.158Z",
        "publishedAt": "2026-06-06T22:01:13.233Z",
        "description": "Envision served as the Construction Manager at Risk to provide reliable cold storage solutions to support district operations across Hillsborough County Public Schools. This involved installing indoor and outdoor walk-in freezers and coolers at seven sites: Chiaramonte Elementary, Collins PreK-8, Eisenhower Middle, Forest Hills Elementary, King High, Lomax Elementary, and Miles Elementary. \n\nExtended work hours, weekend shifts, and increased manpower allowed our team to simultaneously manage work across all seven schools for efficiency and timeliness. Additionally, two-week look-ahead schedules and constant communication with trade partners kept the work aligned across each site. This proactive approach allowed our team to successfully reach substantial completion on time, ready for resumed school operations in the fall. \n",
        "beck": null
      },
      {
        "id": 140,
        "documentId": "ha3um6xho9zv4pl47ryhv7p6",
        "title": "Hillsborough County Public Schools Liberty Middle School Play Court Cover ",
        "slug": "hillsborough-county-public-schools-liberty-middle-school-play-court-cover",
        "completed": "2023-08-01",
        "location": "Tampa, FL",
        "area": "41,140 SF",
        "createdAt": "2026-02-20T01:01:48.875Z",
        "updatedAt": "2026-06-04T04:27:35.363Z",
        "publishedAt": "2026-06-04T04:27:35.429Z",
        "description": "With its 20,790 SF field, 880 SF CMU building, and 19,470 SF court, the new Liberty Middle School Play Court Cover accommodates a large variety of sports for Liberty and the City of Tampa. The final product is 41,140 SF and includes a synthetic turf field with a pre-engineered metal play court cover, three basketball courts, three volleyball courts, three tennis courts, four pickleball courts, two office spaces, two bathrooms, a first aid room, an equipment room, and an electrical closet. Our team overcame construction delays caused by COVID-19, reaching substantial completion after just eight months. ",
        "beck": null
      },
      {
        "id": 257,
        "documentId": "zrrpmn3l2wsbh8caczll5pv3",
        "title": "USL Super League Stadium",
        "slug": "usl-super-league-stadium",
        "completed": "2024-07-01",
        "location": "Tampa, FL",
        "area": "5,000 seats",
        "createdAt": "2026-02-02T23:33:22.308Z",
        "updatedAt": "2026-07-02T02:45:47.109Z",
        "publishedAt": "2026-07-02T02:45:47.197Z",
        "description": "The Tampa Bay USL Super League Stadium project transformed the Blake High School stadium into a professional sports facility, welcoming our city’s first professional women’s soccer team: Tampa Bay Sun FC. The stadium continues to house Blake High School’s football team as well, bringing both student and professional athletes to the heart of Tampa. Stadium upgrades include FIFA-approved turf, enhanced locker rooms, expanded concession facilities, new “fan zones,” a state-of-the-art scoreboard, pre-built VIP box offices, and an increase in seating capacity from 1,800 to over 5,000. ",
        "beck": null
      },
      {
        "id": 148,
        "documentId": "xaog3umx2asdetdag46ncrco",
        "title": "Hillsborough County Public Schools Track Repair & Resurfacing ",
        "slug": "track-repair-and-resurfacing-armwood-jefferson-and-king-high-schools",
        "completed": "2019-01-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-20T00:42:41.082Z",
        "updatedAt": "2026-06-05T14:17:37.050Z",
        "publishedAt": "2026-06-05T14:17:37.112Z",
        "description": "Envision provided site supervision for the sod replacement and replacement of three existing tracks at Armwood, Jefferson, and King high schools. ",
        "beck": true
      },
      {
        "id": 149,
        "documentId": "alj31wp75hr5jh2k5qwxj46y",
        "title": "Warren Hope Dawson Elementary School Renovations & Canopy Cover",
        "slug": "warren-hope-dawson-elementary-school-renovations-and-canopy-cover",
        "completed": "2017-09-01",
        "location": "Tampa,  FL",
        "area": null,
        "createdAt": "2026-06-05T12:46:41.736Z",
        "updatedAt": "2026-06-05T14:19:06.768Z",
        "publishedAt": "2026-06-05T14:19:06.832Z",
        "description": "Envision served as a construction management partner to The Beck Group in building Warren Hope Dawson Elementary School—a project executed to accommodate a growing population and relieve overcrowding at Collins, Summerfield, and Sessums elementary schools.  \n\nNamed after a veteran civil rights attorney who fought to desegregate Hillsborough County Public Schools, the six-building elementary school holds three two-story classrooms, a single-story administration building, a single-story cafeteria and auditorium, and an ancillary building. Envision furnished and installed engineered stairway canopy covers in two locations across the 83,000 SF school, reducing stair maintenance needs and providing shade to students. ",
        "beck": true
      }
    ]
  },
  {
    "id": 30,
    "documentId": "cpua16q5frvkfx9u3fnaq3gu",
    "name": "Government",
    "slug": "government",
    "createdAt": "2026-06-05T16:50:48.382Z",
    "updatedAt": "2026-06-05T17:18:19.048Z",
    "publishedAt": "2026-06-05T17:18:19.090Z",
    "description": "Civic buildings and municipal facilities where compliance, security, and public trust are non-negotiable",
    "image": {
      "id": 293,
      "documentId": "d9dn6eir92c106izqf9360rv",
      "name": "GO_DundeePark_ExtD_07.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 3936,
      "height": 3936,
      "formats": {
        "large": {
          "ext": ".jpg",
          "url": "https://ik.imagekit.io/pnixsw7lg/main-website/GO_Dundee_Park_Ext_D_07_9a48433d91.jpg?updatedAt=1780678285919&tr=w-1000%2Ch-1000&ik-s=fa0b8f288d985c84574cc00321d3ba56d50c6786",
          "hash": "large_GO_Dundee_Park_Ext_D_07_9a48433d91",
          "mime": "image/jpeg",
          "name": "large_GO_DundeePark_ExtD_07.jpg",
          "path": null,
          "size": 260.05,
          "width": 1000,
          "height": 1000,
          "provider": "imagekit",
          "sizeInBytes": 260051,
          "provider_metadata": {
            "fileId": "6a22fe8c5c7cd75eb8c1fbf2"
          }
        },
        "small": {
          "ext": ".jpg",
          "url": "https://ik.imagekit.io/pnixsw7lg/main-website/GO_Dundee_Park_Ext_D_07_9a48433d91.jpg?updatedAt=1780678285919&tr=w-500%2Ch-500&ik-s=326b83d144e331f512b296eb3b4dec6df72843a2",
          "hash": "small_GO_Dundee_Park_Ext_D_07_9a48433d91",
          "mime": "image/jpeg",
          "name": "small_GO_DundeePark_ExtD_07.jpg",
          "path": null,
          "size": 69.48,
          "width": 500,
          "height": 500,
          "provider": "imagekit",
          "sizeInBytes": 69478,
          "provider_metadata": {
            "fileId": "6a22fe8c5c7cd75eb8c1fbb7"
          }
        },
        "medium": {
          "ext": ".jpg",
          "url": "https://ik.imagekit.io/pnixsw7lg/main-website/GO_Dundee_Park_Ext_D_07_9a48433d91.jpg?updatedAt=1780678285919&tr=w-750%2Ch-750&ik-s=0d0a8fe9333577926dafa5799fb7b2f826467964",
          "hash": "medium_GO_Dundee_Park_Ext_D_07_9a48433d91",
          "mime": "image/jpeg",
          "name": "medium_GO_DundeePark_ExtD_07.jpg",
          "path": null,
          "size": 146.18,
          "width": 750,
          "height": 750,
          "provider": "imagekit",
          "sizeInBytes": 146178,
          "provider_metadata": {
            "fileId": "6a22fe8c5c7cd75eb8c1fbac"
          }
        },
        "thumbnail": {
          "ext": ".jpg",
          "url": "https://ik.imagekit.io/pnixsw7lg/main-website/GO_Dundee_Park_Ext_D_07_9a48433d91.jpg?updatedAt=1780678285919&tr=w-156%2Ch-156&ik-s=80c6133aca1d86a9e301da46762bb642afbda12c",
          "hash": "thumbnail_GO_Dundee_Park_Ext_D_07_9a48433d91",
          "mime": "image/jpeg",
          "name": "thumbnail_GO_DundeePark_ExtD_07.jpg",
          "path": null,
          "size": 8.08,
          "width": 156,
          "height": 156,
          "provider": "imagekit",
          "sizeInBytes": 8083,
          "provider_metadata": {
            "fileId": "6a22fe8c5c7cd75eb8c1fb3a"
          }
        }
      },
      "hash": "GO_Dundee_Park_Ext_D_07_9a48433d91",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 2900.49,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/GO_Dundee_Park_Ext_D_07_9a48433d91.jpg?updatedAt=1780678285919",
      "previewUrl": null,
      "provider": "local",
      "provider_metadata": {
        "fileId": "6a22fe8d5c7cd75eb8c1ffa1"
      },
      "createdAt": "2026-06-05T16:51:25.938Z",
      "updatedAt": "2026-06-05T16:51:25.938Z",
      "publishedAt": "2026-06-05T16:51:25.938Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 165,
        "documentId": "emqcx0apkwc7rlhcgoefzo7x",
        "title": "Parks Department Dundee Park Improvements",
        "slug": "parks-department-dundee-park-improvements",
        "completed": "2025-04-01",
        "location": "Tampa, FL",
        "area": "10,650 SF",
        "createdAt": "2026-06-05T16:49:19.624Z",
        "updatedAt": "2026-06-05T22:37:24.003Z",
        "publishedAt": "2026-06-05T22:37:24.081Z",
        "description": "Sitting in the heart of the Tampa neighborhood Sunset Park, the peaceful Dundee Park received amenity upgrades on this park renovation to enhance visitor experience and safety. Envision provided water and tree protection, installed new sidewalks, and managed traffic control to preserve natural beauty and increase pedestrian safety at the 10,650 SF park.\n\nAlthough allotted an entire month of construction by the City of Tampa, our efficient team completed this project within just two weeks—even after constructing an additional sidewalk across the street per the city’s request. ",
        "beck": null
      }
    ]
  },
  {
    "id": 31,
    "documentId": "c65nrciokfglct5ur6gmixwm",
    "name": "Arts and Entertainment",
    "slug": "arts-and-entertainment",
    "createdAt": "2026-02-12T03:09:15.161Z",
    "updatedAt": "2026-06-08T01:58:06.239Z",
    "publishedAt": "2026-06-08T01:58:06.290Z",
    "description": "Performance venues, galleries, and entertainment spaces built for impact and longevity",
    "image": {
      "id": 65,
      "documentId": "88a9d06aa7de42849f402b5c",
      "name": "leonard-reid-05.JPG",
      "alternativeText": null,
      "caption": null,
      "width": 1024,
      "height": 768,
      "formats": {},
      "hash": "leonard-reid-05_698d0412",
      "ext": ".JPG",
      "mime": "image/jpeg",
      "size": 339.01,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/leonard-reid-05.JPG",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/leonard-reid-05.JPG?updatedAt=1770849298825",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "698d04125c7cd75eb843b930"
      },
      "createdAt": "2026-02-11T22:35:28.133Z",
      "updatedAt": "2026-02-11T22:35:28.133Z",
      "publishedAt": "2026-02-11T22:35:28.133Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 156,
        "documentId": "lvfutxvjxf9qlw9sufxsxryr",
        "title": "TGH Animal Care Center at the Florida Aquarium",
        "slug": "tgh-animal-care-center-at-the-florida-aquarium",
        "completed": "2022-09-01",
        "location": "Tampa, FL",
        "area": "500 SF",
        "createdAt": "2026-02-12T03:13:19.860Z",
        "updatedAt": "2026-06-05T14:29:35.455Z",
        "publishedAt": "2026-06-05T14:29:35.521Z",
        "description": "The TGH Animal Care Center at The Florida Aquarium is a testament to the value of a partnership between organizations dedicated to providing life-saving treatment. In addition to enhancing the treatment environment for 9,000 creatures, the 500 SF buildout also granted aquarium guests a behind-the-scenes view of animal examinations. However, the glass windows that provide this view were not installed at the expense of privacy; their appearance can be switched to frosted when more serious treatments must be performed. \n\nUpon wall demolition, the buildout resulted in a raised floor with a trench drain, a new ceiling and cabinet, new storefront framing, countertops, and LED lighting.",
        "beck": null
      },
      {
        "id": 241,
        "documentId": "onm21tgzx265g9ldhbb919xz",
        "title": "Florida Aquarium Restroom Renovation",
        "slug": "florida-aquarium-restroom-renovation",
        "completed": "2022-12-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-06-08T02:55:46.410Z",
        "updatedAt": "2026-06-08T03:06:39.833Z",
        "publishedAt": "2026-06-08T03:06:39.890Z",
        "description": "The Florida Aquarium Restroom Renovation involved significant interior upgrades to the four main restrooms at their Tampa facility. Reflecting the aquarium’s commitment to quality, the upgraded restrooms feature new epoxy floors, ceiling paint, urinals, fixtures, countertops, can lights, moisture-resistant gypsum boards, LED backlit mirrors, wall-mounted fixtures and automatic sensors, and lavatories with automatic faucets and soap dispensers.",
        "beck": null
      },
      {
        "id": 249,
        "documentId": "l9zm65l5l0zolmxa8reyo09q",
        "title": "Leonard Reid Historic Interior Renovation",
        "slug": "leonard-reid-historic-interior-renovation",
        "completed": "2023-12-01",
        "location": "Sarasota, FL",
        "area": "1,400 SF",
        "createdAt": "2026-06-08T03:10:36.993Z",
        "updatedAt": "2026-06-08T03:12:20.296Z",
        "publishedAt": "2026-06-08T03:12:20.351Z",
        "description": "The Leonard Reid Historic Interior Renovation involved the restoration and renovation of a 1,400 SF historic residence into a museum for the Sarasota African American Cultural Coalition (SAACC). \n\nEnvision performed interior upgrades to include a new bathroom, renovated kitchen, and new gallery space, along with refreshes of paint, ACT, drywall, HVAC, and flooring. Additionally, selective demolition, repair of existing wood siding, paint, and new window film on the building’s exterior created a renewed exterior appearance. These renovations transformed the former home of Leonard Reid, one of Sarasota’s original pioneers, into a welcoming museum space for visitors while preserving the authenticity and heart of the original residence. ",
        "beck": null
      }
    ]
  },
  {
    "id": 19,
    "documentId": "n946opsasuuptr7t80wlrddp",
    "name": "Athletics",
    "slug": "athletics",
    "createdAt": "2026-02-04T01:32:14.977Z",
    "updatedAt": "2026-05-20T21:29:40.769Z",
    "publishedAt": "2026-05-20T21:29:40.807Z",
    "description": "High-performance sports facilities built for athletes and the communities behind them",
    "image": {
      "id": 11,
      "documentId": "5554e33820e14c818474b4aa",
      "name": "usl-super-league-01.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 4056,
      "height": 3040,
      "formats": {},
      "hash": "usl-super-league-01_698295e3",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 9622.27,
      "url": "https://ik.imagekit.io/pnixsw7lg/strapi-uploads/usl-super-league-01.jpg?updatedAt=1770165733176",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/strapi-uploads/usl-super-league-01.jpg?updatedAt=1770165733176&tr=n-ik_ml_thumbnail",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "698295e35c7cd75eb87050b6"
      },
      "createdAt": "2026-02-04T01:34:21.241Z",
      "updatedAt": "2026-04-14T10:11:38.463Z",
      "publishedAt": "2026-02-04T01:34:21.241Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 257,
        "documentId": "zrrpmn3l2wsbh8caczll5pv3",
        "title": "USL Super League Stadium",
        "slug": "usl-super-league-stadium",
        "completed": "2024-07-01",
        "location": "Tampa, FL",
        "area": "5,000 seats",
        "createdAt": "2026-02-02T23:33:22.308Z",
        "updatedAt": "2026-07-02T02:45:47.109Z",
        "publishedAt": "2026-07-02T02:45:47.197Z",
        "description": "The Tampa Bay USL Super League Stadium project transformed the Blake High School stadium into a professional sports facility, welcoming our city’s first professional women’s soccer team: Tampa Bay Sun FC. The stadium continues to house Blake High School’s football team as well, bringing both student and professional athletes to the heart of Tampa. Stadium upgrades include FIFA-approved turf, enhanced locker rooms, expanded concession facilities, new “fan zones,” a state-of-the-art scoreboard, pre-built VIP box offices, and an increase in seating capacity from 1,800 to over 5,000. ",
        "beck": null
      },
      {
        "id": 140,
        "documentId": "ha3um6xho9zv4pl47ryhv7p6",
        "title": "Hillsborough County Public Schools Liberty Middle School Play Court Cover ",
        "slug": "hillsborough-county-public-schools-liberty-middle-school-play-court-cover",
        "completed": "2023-08-01",
        "location": "Tampa, FL",
        "area": "41,140 SF",
        "createdAt": "2026-02-20T01:01:48.875Z",
        "updatedAt": "2026-06-04T04:27:35.363Z",
        "publishedAt": "2026-06-04T04:27:35.429Z",
        "description": "With its 20,790 SF field, 880 SF CMU building, and 19,470 SF court, the new Liberty Middle School Play Court Cover accommodates a large variety of sports for Liberty and the City of Tampa. The final product is 41,140 SF and includes a synthetic turf field with a pre-engineered metal play court cover, three basketball courts, three volleyball courts, three tennis courts, four pickleball courts, two office spaces, two bathrooms, a first aid room, an equipment room, and an electrical closet. Our team overcame construction delays caused by COVID-19, reaching substantial completion after just eight months. ",
        "beck": null
      },
      {
        "id": 210,
        "documentId": "jzqw1lqjxkfibuorpz26th96",
        "title": "University of South Florida Football Practice Fields: Conduit Burial",
        "slug": "university-of-south-florida-football-practice-fields-conduit-burial",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T21:52:40.819Z",
        "updatedAt": "2026-06-08T02:13:12.174Z",
        "publishedAt": "2026-06-08T02:13:12.272Z",
        "description": "Envision completed conduit burial at the University of South Florida Football Practice Fields to support future electrical infrastructure for a planned coaching tower. As construction progressed on the two new football fields, our team was engaged to provide a quick-turn solution ahead of the scheduled turf installation.\n\nWith a limited window before the turf was placed, Envision provided timely pricing, coordinated the required electrical pathway work, and completed installation before the area was no longer accessible. The work was delivered within an active campus environment while helping USF preserve future build-out flexibility without impacting the overall field construction schedule.",
        "beck": null
      },
      {
        "id": 215,
        "documentId": "opxb566soyon8khjggxgyy8r",
        "title": "Hillsborough County Public Schools McLane Middle School Fire Restoration ",
        "slug": "hillsborough-county-public-schools-mc-lane-middle-school-fire-restoration",
        "completed": "2019-07-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-06-05T14:22:35.339Z",
        "updatedAt": "2026-06-08T02:37:10.430Z",
        "publishedAt": "2026-06-08T02:37:10.496Z",
        "description": "In the middle of summer in 2019, a lightning strike caused fire damage to McLane Middle School’s seventh grade building—requiring a timely response for a key portion of the campus. With the affected building requiring removal, the project moved forward with taking the building down with the help of Beck-Envision and creating a new STEM-driven outdoor classroom in its place.\n\nWith Envision serving as The Beck Group’s construction management partner, our team safely demolished the building while keeping surrounding classrooms intact. Additionally, parking lot repairs and installation of new aluminum canopies, sidewalks, and 14,000 SF of hand-graded sod were performed to help restore surrounding areas. ",
        "beck": null
      }
    ]
  },
  {
    "id": 21,
    "documentId": "nltsz23vbh1ft96wmzkaeal5",
    "name": "Aviation",
    "slug": "aviation",
    "createdAt": "2026-02-13T04:09:47.891Z",
    "updatedAt": "2026-05-20T21:30:15.462Z",
    "publishedAt": "2026-05-20T21:30:15.650Z",
    "description": "Complex, code-driven environments where safety and schedule are non-negotiable",
    "image": {
      "id": 86,
      "documentId": "9d9eb37bcbe54ec78b9e3e44",
      "name": "IMG_9501.JPG",
      "alternativeText": null,
      "caption": null,
      "width": 5184,
      "height": 3456,
      "formats": {},
      "hash": "IMG_9501_698e9cf6",
      "ext": ".JPG",
      "mime": "image/jpeg",
      "size": 6097.28,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/IMG_9501.JPG",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/IMG_9501.JPG?updatedAt=1770953975277",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "698e9cf65c7cd75eb8a83419"
      },
      "createdAt": "2026-02-13T03:39:41.310Z",
      "updatedAt": "2026-02-13T04:08:31.411Z",
      "publishedAt": "2026-02-13T03:39:41.310Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 122,
        "documentId": "lz4zp6pjgpmkdu3crag74h8i",
        "title": "HCAA Tampa International Airport Airside A, C and F Restroom Renovations",
        "slug": "hcaa-tampa-international-airport-airside-a-c-and-f-restroom-renovations",
        "completed": "2023-12-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-13T03:32:40.524Z",
        "updatedAt": "2026-06-04T04:20:51.715Z",
        "publishedAt": "2026-06-04T04:20:51.781Z",
        "description": "This renovation refurbished and expanded public restrooms to enhance maintainability, improve the overall appearance, and provide a new layout with larger stalls. It also included an expansion to the Airside C building to accommodate offices displaced by the expansion.\n\nTo ensure a successful project, Envision and The Beck Group designed and planned efficiently using the Building Information Model (BIM), modeled passenger and pedestrian flow through the airport, and applied new technologies in bathroom best practices (such as latch sensors and interactive monitors that allow passengers to indicate their level of satisfaction with the restroom).\n\n_In collaboration with our construction management partner, The Beck Group, Envision provided comprehensive support across all phases of the project to include executive oversight, project management, field supervision, preconstruction services, and client engagement. Our integrated role ensured alignment, continuity, and excellence from pursuit to delivery._",
        "beck": true
      },
      {
        "id": 123,
        "documentId": "ezzv00l2c7gbkg8zr1bwxu3q",
        "title": "HCAA Tampa International Airport Airside E Roof Renovation ",
        "slug": "hcaa-tampa-international-airport-airside-e-roof-renovation",
        "completed": "2026-08-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-13T03:38:59.804Z",
        "updatedAt": "2026-06-04T04:21:05.552Z",
        "publishedAt": "2026-06-04T04:21:05.641Z",
        "description": "Envision and The Beck Group were selected by the Hillsborough County Aviation Authority to provide design-build services for the roof replacement at Airside E. Due to persistent moisture intrusion and ongoing maintenance challenges, the existing standing seam metal roof had reached a premature end of service life. The scope of work includes removing and replacing the standing seam metal roofing system, upgrading the low-slope asphaltic roofing, and wet sealing the curtain wall glazing in targeted areas to extend its service life.\n\nFurther investigation and testing will identify any additional remediation needs as part of the early phases of the work. All upgrades are being completed within an active terminal environment, requiring careful planning and phased coordination to avoid disruption to airport operations.\n\nIn collaboration with our CM partner, The Beck Group, Envision provided comprehensive support across all phases of the project to include executive oversight, project management, field supervision, preconstruction services, and client engagement. Our integrated role ensured alignment, continuity, and excellence from pursuit to delivery.",
        "beck": null
      },
      {
        "id": 124,
        "documentId": "mrjsawzxxvq206iex6ku4c66",
        "title": "HCAA Tampa International Airport Airside F Reroof & Envelope Repair",
        "slug": "hcaa-tampa-international-airport-airside-f-reroof-and-envelope-repair",
        "completed": "2021-01-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-13T03:42:32.805Z",
        "updatedAt": "2026-06-04T04:21:21.156Z",
        "publishedAt": "2026-06-04T04:21:21.232Z",
        "description": "Envision and The Beck Group provided preconstruction, architecture, construction, and VBG for this project. Our team evaluated and replaced the original barrel vault standing seam roof, gutters, and storm drainage systems. In addition, extensive rehabilitation of glazing systems and other miscellaneous envelope conditions were added during evaluation and design phases. The repair and replacement of these systems is essential to maintain top HCAA in extending the operational life of the Airside F building for another 25 years.\n\nIn collaboration with our CM partner, The Beck Group, Envision provided comprehensive support across all phases of the project to include executive oversight, project management, field supervision, preconstruction services, and client engagement. Our integrated role ensured alignment, continuity, and excellence from pursuit to delivery.",
        "beck": true
      },
      {
        "id": 154,
        "documentId": "wvozbdgr7e0zp5p2nxhfnz9v",
        "title": "HCAA Tampa International Airport Airside E Roof Renovation ",
        "slug": "hcaa-tampa-international-airport-airside-e-roof-renovation-1",
        "completed": "2021-12-01",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-02-13T04:03:50.655Z",
        "updatedAt": "2026-06-05T14:26:38.336Z",
        "publishedAt": "2026-06-05T14:26:38.413Z",
        "description": "Envision and The Beck Group provided master planning, architecture, preconstruction, and construction services. This integrated project encompassed the expansion of Access Control Systems to the Main Terminal, Airside guide-way doors, and all Airside jetbridge doors. Additionally, the Video Management System was modified and expanded to replace all existing analog cameras with IP addressable cameras and provide additional cameras for a comprehensive surveillance system throughout the campus.\n\nIn collaboration with our CM partner, The Beck Group, Envision provided comprehensive support across all phases of the project to include executive oversight, project management, field supervision, preconstruction services, and client engagement. Our integrated role ensured alignment, continuity, and excellence from pursuit to delivery.",
        "beck": true
      }
    ]
  },
  {
    "id": 22,
    "documentId": "syuq2m7m8a43s3cuuvwfjqjr",
    "name": "Business and Corporate",
    "slug": "business-and-corporate",
    "createdAt": "2026-02-13T04:11:19.675Z",
    "updatedAt": "2026-05-20T21:30:27.592Z",
    "publishedAt": "2026-05-20T21:30:27.627Z",
    "description": "Headquarters, tenant suites, and corporate interiors built to the standard your business demands",
    "image": {
      "id": 91,
      "documentId": "171ba84f57ec4fc89b3606a3",
      "name": "IMG_7625.jpeg",
      "alternativeText": null,
      "caption": null,
      "width": 960,
      "height": 540,
      "formats": {},
      "hash": "IMG_7625_698ea319",
      "ext": ".jpeg",
      "mime": "image/jpeg",
      "size": 148.09,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/IMG_7625.jpeg",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/IMG_7625.jpeg?updatedAt=1770955545519",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "698ea3195c7cd75eb8ce2ad0"
      },
      "createdAt": "2026-02-13T04:05:55.130Z",
      "updatedAt": "2026-02-13T04:05:55.130Z",
      "publishedAt": "2026-02-13T04:05:55.130Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 256,
        "documentId": "uopyyxks41w3g9g4p9y2x9ek",
        "title": "5000 Acline Drive Office Build Out",
        "slug": "5000-acline-drive-office-build-out",
        "completed": "2024-11-01",
        "location": "Tampa, FL",
        "area": "4,500 SF",
        "createdAt": "2026-02-13T04:25:08.719Z",
        "updatedAt": "2026-06-17T16:21:04.843Z",
        "publishedAt": "2026-06-17T16:21:04.961Z",
        "description": "The 5000 Acline Drive Office Build Out was designed with many factors in mind, including potential for future growth, the flow of the office, aesthetic of the interior space, and provision of a welcoming feel. Built from shell space, the project resulted in seven offices, a “cubicle” work area with three work spaces, one large conference room, one small conference room, two restrooms, and a break room with a kitchenette at a total of 4,500 SF. ",
        "beck": null
      },
      {
        "id": 168,
        "documentId": "l41lq085asbk580idz6r0ded",
        "title": "Suncoast Tampa REALTORS Office Renovation ",
        "slug": "suncoast-tampa-realtors-office-renovation",
        "completed": "2017-05-01",
        "location": "Tampa, FL",
        "area": "922 SF",
        "createdAt": "2026-02-13T04:21:16.158Z",
        "updatedAt": "2026-06-06T03:47:55.701Z",
        "publishedAt": "2026-06-06T03:47:55.754Z",
        "description": "Envision completed preconstruction, design-assist, and construction services for this 17,000 SF office interior refresh. After having gone 15 years without renovation, the outdated finishes and layout were modernized to improve the office’s appearance, flow, and efficiency. To meet our client’s needs while also maintaining a safe environment for the staff to work in throughout construction, collaboration was key in the programming phase of this interior renovation. \n\nOperations remained active during construction, but hard barriers ensured the safety of the staff, maintained proper air quality, and allowed construction to safely take place near main areas. Careful planning during the due diligence period allowed for a streamlined approach in every project phase without interrupting our client’s daily workflow. ",
        "beck": null
      },
      {
        "id": 245,
        "documentId": "r6cpyqx8jv9nwkxhykz83jwv",
        "title": "Focus Flooring Office Build-Out",
        "slug": "focus-flooring-office-build-out",
        "completed": "2023-05-01",
        "location": "Tampa, Fl",
        "area": "1,500 SF",
        "createdAt": "2026-02-13T04:18:04.561Z",
        "updatedAt": "2026-06-08T03:09:59.887Z",
        "publishedAt": "2026-06-08T03:09:59.936Z",
        "description": "With the goal of creating more workspaces with 1,500 SF of space, the Focus Flooring Office Build-Out doubled capacity from 10 employees to 20. The office was built out and renovated to include a new kitchenette area, one large workspace, two new offices with adjoining cubicle work spaces, and a conference room. New finishes were implemented as well, including new flooring and base throughout, metal framing and drywall, doors and hardware, paint, ACT, light fixtures, and signage.",
        "beck": null
      },
      {
        "id": 169,
        "documentId": "ex15j6ugv9zqyvlyjtryubri",
        "title": "Office Headquarters Build-Out at The Motor Enclave ",
        "slug": "office-headquarters-build-out-at-the-motor-enclave",
        "completed": "2026-07-01",
        "location": "Tampa, FL",
        "area": "2,714 SF",
        "createdAt": "2026-02-13T04:07:16.524Z",
        "updatedAt": "2026-06-06T04:02:51.180Z",
        "publishedAt": "2026-06-06T04:02:51.254Z",
        "description": "Home to the largest Private Garage Community in the world, this Office Headquarters Build-Out at The Motor Enclave transformed a pre-engineered metal warehouse into a fully customized, multi-use office and collaboration space. Having blended industrial infrastructure with high-performing interior improvements, the design of the space readily supports a fast-paced, flexible work environment.\n\nThe 2,714 SF office features six enclosed offices, two conference rooms, four restrooms, two full bathrooms with showers, a full kitchen, a washer and dryer area, and a second-level balcony overlooking the track. To support evolving office needs, the layout includes three removable partition walls, a dedicated technology room, a soundproof phone booth, and open common areas for collaboration and informal gatherings.",
        "beck": null
      },
      {
        "id": 253,
        "documentId": "ge6xmusfc9mcth3h96189g24",
        "title": "Greater Tampa Realtors",
        "slug": "greater-tampa-realtors",
        "completed": "2026-02-01",
        "location": "Tampa, FL",
        "area": "17,000 SF ",
        "createdAt": "2026-06-08T10:21:01.579Z",
        "updatedAt": "2026-06-08T10:21:03.898Z",
        "publishedAt": "2026-06-08T10:21:03.951Z",
        "description": "Envision completed preconstruction, design-assist, and construction services for this 17,000 SF office interior renovation. After having gone 15 years without renovation, the outdated finishes and layout were modernized to improve the office’s appearance, flow, and efficiency. To meet our client’s needs while also maintaining a safe environment for the staff to work in throughout construction, collaboration was key in the programming phase of this interior renovation. \n\nOperations remained active during construction, but hard barriers ensured the safety of the staff, maintained proper air quality, and allowed construction to safely take place near main areas. Careful planning during the due diligence period allowed for a streamlined approach in every project phase without interrupting our client’s daily workflow. ",
        "beck": null
      }
    ]
  },
  {
    "id": 23,
    "documentId": "ku1tju65s27b5lvuakkqvh8t",
    "name": "Higher Education",
    "slug": "higher-education",
    "createdAt": "2026-02-18T10:28:25.163Z",
    "updatedAt": "2026-05-20T21:31:04.343Z",
    "publishedAt": "2026-05-20T21:31:04.378Z",
    "description": "Campus builds and institutional projects that balance complexity with long-term vision",
    "image": {
      "id": 123,
      "documentId": "6d0ded2991fb41f9becb1527",
      "name": "UT MPB - Exteriors - Front Shift Pano - trees removed.webp",
      "alternativeText": null,
      "caption": null,
      "width": 4000,
      "height": 2522,
      "formats": {},
      "hash": "UT_MPB_-_Exteriors_-_Front_Shift_Pano_-_trees_removed_699593c3",
      "ext": ".webp",
      "mime": "image/webp",
      "size": 3228.57,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/UT%20MPB%20-%20Exteriors%20-%20Front%20Shift%20Pano%20-%20trees%20removed.webp",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/UT%20MPB%20-%20Exteriors%20-%20Front%20Shift%20Pano%20-%20trees%20removed.webp?updatedAt=1771410371972",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "699593c35c7cd75eb8166ff7"
      },
      "createdAt": "2026-02-18T10:26:28.183Z",
      "updatedAt": "2026-02-18T10:26:28.183Z",
      "publishedAt": "2026-02-18T10:26:28.183Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 135,
        "documentId": "sw9p4z534iynri3szwtihvym",
        "title": "University of South Florida Judy Genshaft Honors College",
        "slug": "university-of-south-florida-judy-genshaft-honors-college",
        "completed": "2023-07-01",
        "location": "Tampa, FL",
        "area": "86,845 SF",
        "createdAt": "2026-02-18T10:30:34.714Z",
        "updatedAt": "2026-06-04T04:25:52.077Z",
        "publishedAt": "2026-06-04T04:25:52.138Z",
        "description": "The Judy Genshaft Honors College at University of South Florida provides centralization for Honors students and faculty who were previously scattered on campus. Constructed by Beck-Envision, the new-build structure is 86,845 SF and five stories tall with zero straight lines in its design. \n\nThe building is particularly characterized by its reflective, two-toned outside tiles, which were imported from Italy and switch colors throughout the day. When the sun is low, their color is a pale maroon; when the sun is high, their color is a deep sage. Not only do the reflective metal tiles contribute to the building’s beauty, but they also adapt to Tampa’s climate by reducing heat absorption.  \n\nInside the Honors College are 36 studying cubbies stacked in levels, classrooms with noise-canceling acoustic panels, performance and creative spaces, an Art and Food studio with a full kitchen, offices for faculty and administrative use, indoor and outdoor lounge areas, an outdoor amphitheater, an outdoor classroom, a multi-purpose lobby with large-scale event capacity, and a Buddy Brew open to USF and the public.  \n",
        "beck": true
      },
      {
        "id": 158,
        "documentId": "sccmrlb1w346x1n2qs467ii1",
        "title": "University of South Florida St. Petersburg Davis Hall Renovation",
        "slug": "university-of-south-florida-st-petersburg-davis-hall-renovation",
        "completed": "2021-01-01",
        "location": "Tampa, FL",
        "area": "35,000 SF",
        "createdAt": "2026-02-18T11:20:48.828Z",
        "updatedAt": "2026-06-05T16:37:01.201Z",
        "publishedAt": "2026-06-05T16:37:01.275Z",
        "description": "The University of South Florida St. Petersburg Davis Hall Renovation transformed the building’s dated, second-floor academic space into a flexible and modern space for students and faculty. The Beck-Envision team renovated the 35,000 SF floor to include 13 classrooms with new audio/visual equipment, lighting, and furniture, as well as faculty offices, student lounges, and research space. Additionally, students now enjoy greater views of Bayboro Harbor and Harborwalk at the sides of the building—the scenery that inspired the interior design choices of the renovation. ",
        "beck": true
      },
      {
        "id": 137,
        "documentId": "m9x8k3yx5rju3owwsyi3iss4",
        "title": "University of South Florida St. Petersburg Osprey Suites & Dining Hall ",
        "slug": "university-of-south-florida-st-petersburg-osprey-suites-and-dining-hall",
        "completed": "2020-07-01",
        "location": "Tampa, FL",
        "area": "125,000 SF",
        "createdAt": "2026-02-20T00:36:17.597Z",
        "updatedAt": "2026-06-04T04:26:25.354Z",
        "publishedAt": "2026-06-04T04:26:25.418Z",
        "description": "The Osprey Suites residence hall at University of South Florida St. Petersburg not only expanded student housing from 550 to over 900 beds, but also gave the campus its first full-service, 400-seat dining facility. Envision served as the MBE CM partner on this project with our partner The Beck Group, carrying out general labor and self-performing all tile and wall. \n\nThe 125,000 SF, six-story building includes a lounge, study area, and community kitchen on the first floor. The other five floors have dormitories, where residents of upper levels enjoy incredible views of the waterfront and downtown St. Petersburg. Upon construction of the sustainable, LEED-certified building, lumber from the oak trees that were cleared in the process was salvaged and incorporated into the hall’s furniture and design features.",
        "beck": true
      },
      {
        "id": 138,
        "documentId": "ortrwd1dlx4etmze58nlpdgt",
        "title": "University of Tampa Grand Center Residence Hall",
        "slug": "university-of-tampa-grand-center-residence-hall",
        "completed": "2024-09-01",
        "location": "Tampa, FL",
        "area": "510,320 SF",
        "createdAt": "2026-02-18T10:27:25.519Z",
        "updatedAt": "2026-06-04T04:26:35.952Z",
        "publishedAt": "2026-06-04T04:26:36.011Z",
        "description": "Located just north of where Babe Ruth hit his longest home run, University of Tampa’s Multipurpose Center was built by Beck-Envision to serve as a combination residence hall, parking deck, classroom, and office building. At 510,320 SF—over two times the size of the UT Vaughn Center—it has taken the title of the largest building at the university. \n\nThe center provides housing and parking for hundreds of students with a 13,000 SF skypark, 600 beds, 130 restroom pods, 64 offices, 22 EV chargers, 10 levels, five classrooms, four departments, a bike storage facility, and a Starbucks. ",
        "beck": true
      },
      {
        "id": 162,
        "documentId": "gw3udn1p1vdrts7s0k3robli",
        "title": "University of South Florida FAO ADA Restroom Remodel",
        "slug": "university-of-south-florida-fao-ada-restroom-remodel",
        "completed": "2025-02-01",
        "location": "Tampa, FL",
        "area": "50 SF",
        "createdAt": "2026-06-05T16:42:28.166Z",
        "updatedAt": "2026-06-05T16:43:32.367Z",
        "publishedAt": "2026-06-05T16:43:32.476Z",
        "description": "Envision’s first independently-owned project with the University of South Florida, the USF FAO Building ADA Restroom Remodel, served as a major milestone. The project converted an existing storage room into a 50 SF, ADA-Envision’s first independently-owned project with the University of South Florida, the USF FAO Building ADA Restroom Remodel served as a major milestone. This renovation involved significant electrical, HVAC, and plumbing upgrades to convert an existing storage area into a 50 SF, ADA-compliant unisex bathroom. Additionally, our team installed drywall and framing, floor and wall tile finishes, ceiling modifications, and ADA-compliant fixtures and accessories.\n\nOur team worked closely with USF to coordinate and execute the project schedule, ensuring minimal disruption to faculty and campus operations. Recognizing the importance of maintaining a functional and accessible environment for staff to work, the construction schedule was coordinated to take place predominantly during the summer due to reduced foot traffic on campus. This strategic approach allowed for seamless integration of the new bathroom into the existing infrastructure while ensuring that the university’s day-to-day activities remained largely unaffected. \ncompliant unisex bathroom. In addition to the significant electrical, HVAC, and plumbing upgrades performed, our team installed drywall and framing, floor and wall tile finishes, ceiling modifications, and ADA-compliant fixtures and accessories.",
        "beck": null
      },
      {
        "id": 195,
        "documentId": "j9znc48voi9gh79cxm27tmso",
        "title": "University of South Florida Feed-A-Bull Food Pantry Renovations",
        "slug": "university-of-south-florida-feed-a-bull-food-pantry-renovations",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T21:50:58.191Z",
        "updatedAt": "2026-06-06T21:50:59.291Z",
        "publishedAt": "2026-06-06T21:50:59.361Z",
        "description": "Envision completed an interior build-out at the University of South Florida to expand and improve the university’s Feed-A-Bull Food Pantry. The renovation created a larger, more functional space to support the pantry’s student-serving operations.\n\nThe scope included demolition, new walls, doors, electrical runs, ceilings, paint, flooring, and installation of a commercial refrigerator. Because the work took place on an active campus, Envision coordinated barricades, site separation, and access controls to minimize disruption while maintaining a clean, organized work area.",
        "beck": null
      },
      {
        "id": 201,
        "documentId": "rad8nftmzhk71biyjk4bfqx8",
        "title": "University of South Florida MDA Multiple Building Upgrades",
        "slug": "university-of-south-florida-mda-multiple-building-upgrades",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T21:56:05.594Z",
        "updatedAt": "2026-06-06T21:56:06.956Z",
        "publishedAt": "2026-06-06T21:56:06.997Z",
        "description": "Envision completed multiple building upgrades at the University of South Florida’s MDA facilities, improving entry points, access-control readiness, and exterior connectivity across the campus environment.\n\nThe scope included installation of a new storefront entry door, new hollow metal double doors with associated hardware, added electrical receptacles to support access control systems, and construction of a new concrete sidewalk at the side entrance. Envision also coordinated access control and signage by others, while our SPD team self-performed ceiling modifications, minor patchwork, and final cleaning for a complete project turnover.",
        "beck": null
      },
      {
        "id": 203,
        "documentId": "k345bi6dbxykckk6w1w9kt15",
        "title": "University of South Florida NES 329 Lab Renovation",
        "slug": "university-of-south-florida-nes-329-lab-renovation",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T21:57:56.303Z",
        "updatedAt": "2026-06-06T21:57:58.299Z",
        "publishedAt": "2026-06-06T21:57:58.343Z",
        "description": "Envision completed lab improvements within USF’s NES Room 329, adding a new faucet and delivering a customized cabinetry solution to replace the original cabinets. Our SPD team self-performed vinyl base installation, painting, drywall repairs, patchwork, and final cleaning to provide a complete, polished turnover.",
        "beck": null
      },
      {
        "id": 205,
        "documentId": "uczefyhaane4wymxwa4dcklg",
        "title": "University of South Florida Office of Veterans Success RenovationsUniversity of South Florida Office of Veterans Success Renovations",
        "slug": "university-of-south-florida-office-of-veterans-success-renovations-university-of-south-florida-office-of-veterans-success-renovations",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T21:59:24.125Z",
        "updatedAt": "2026-06-06T21:59:25.433Z",
        "publishedAt": "2026-06-06T21:59:25.478Z",
        "description": "Envision completed interior renovations for the University of South Florida’s Office of Veterans Success across two campus buildings, refreshing the spaces to better support student-facing operations.\n\nThe scope included selective demolition, new flooring, MEP modifications, privacy window film, ACT ceiling updates, and a new coded-entry door lock. Our SPD team self-performed demolition, ACT repairs, door hardware, and final cleaning to support a complete, coordinated turnover.",
        "beck": null
      }
    ]
  },
  {
    "id": 25,
    "documentId": "t1tnk7sx02ferqthy031fau1",
    "name": "Healthcare",
    "slug": "healthcare",
    "createdAt": "2026-05-14T10:03:18.136Z",
    "updatedAt": "2026-05-20T21:33:38.351Z",
    "publishedAt": "2026-05-20T21:33:38.386Z",
    "description": "Medical offices, clinics, and healthcare facilities where patient safety drives every decision",
    "image": {
      "id": 68,
      "documentId": "9f89f373333c43a8985113de",
      "name": "tgh-animal-care-center-02.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 2560,
      "height": 1378,
      "formats": {},
      "hash": "tgh-animal-care-center-02_698d44c9",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 233.41,
      "url": "https://ik.imagekit.io/pnixsw7lg/main-website/tgh-animal-care-center-02.jpg",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/main-website/tgh-animal-care-center-02.jpg?updatedAt=1770865865533",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "698d44c95c7cd75eb8dead0b"
      },
      "createdAt": "2026-02-12T03:11:13.023Z",
      "updatedAt": "2026-02-12T03:12:27.532Z",
      "publishedAt": "2026-02-12T03:11:13.023Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 131,
        "documentId": "jkvx9t81d7n7rg58hko71p8q",
        "title": "Moffitt Cancer Center LINAC Vault Replacement ",
        "slug": "project",
        "completed": "2025-07-23",
        "location": "Tampa, FL",
        "area": null,
        "createdAt": "2026-05-14T10:04:19.313Z",
        "updatedAt": "2026-06-04T04:24:16.771Z",
        "publishedAt": "2026-06-04T04:24:16.861Z",
        "description": "The Moffitt LINAC Vault Replacement was a three-package effort at Moffitt Cancer Center to replace the LINAC in MCC Vault 3, consolidate the MA work area in MCC1, and install a dedicated UPS in MCC1 Room 1939 to support Radiation Oncology LINACs. Scope of work includes demolition, cabinets, doors, frames & hardware, interior glazing, drywall, acoustical ceilings, flooring, painting, specialties, fire protection, plumbing, HVAC, and electrical.\n_\nIn collaboration with our CM partner, The Beck Group, Envision provided comprehensive support across all phases of the project to include executive oversight, project management, field supervision, preconstruction services, and client engagement. Our integrated role ensured alignment, continuity, and excellence from pursuit to delivery._",
        "beck": true
      },
      {
        "id": 171,
        "documentId": "fzkwqfrt600bbn0bd1gshxxu",
        "title": "Moffitt Cancer Center Founder’s Garden Railing & Shear Wall Painting",
        "slug": "moffitt-cancer-center-founder-s-garden-railing-and-shear-wall-painting",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:27:17.840Z",
        "updatedAt": "2026-06-06T19:27:19.323Z",
        "publishedAt": "2026-06-06T19:27:19.369Z",
        "description": "Envision completed stucco repairs and painting improvements at Moffitt Cancer Center’s Founder’s Garden, refreshing existing railings and shear wall finishes to support long-term durability, safety, and appearance. Our team implemented containment and barricades to maintain a safe environment for patients, staff, and visitors throughout construction. With work taking place in an active healthcare setting, our team remained flexible and performed off-hours work as needed to minimize disruption and complete the project efficiently.",
        "beck": null
      },
      {
        "id": 173,
        "documentId": "x1pdwpal5wzacpgto4ws3zne",
        "title": "Moffitt Cancer Center Founder’s Garden Storm Pass Through",
        "slug": "moffitt-cancer-center-founder-s-garden-storm-pass-through",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:28:36.649Z",
        "updatedAt": "2026-06-06T19:29:50.545Z",
        "publishedAt": "2026-06-06T19:29:50.593Z",
        "description": "Envision completed a drainage improvement at Moffitt Cancer Center’s Founder’s Garden to better manage stormwater flow near an existing sidewalk and support safe, reliable access through the area. The scope included installing a 6-inch corrugated pipe connected to a new 12-inch square catch basin on the opposite side of the sidewalk, tying the new system into the existing drainage infrastructure.\n\nTo complete the work efficiently ahead of seasonal rain impacts, our team coordinated off-hours work in an active healthcare environment. The area was carefully excavated, stabilized, and restored with cement backfill and soil cover to support long-term performance while maintaining safe access for patients, staff, and visitors.",
        "beck": null
      },
      {
        "id": 177,
        "documentId": "tslehen8bg6egikvhaj11g04",
        "title": "Moffitt Cancer Center Trash Compactor Relocation ",
        "slug": "moffitt-cancer-center-trash-compactor-relocation",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:35:01.177Z",
        "updatedAt": "2026-06-06T19:35:03.125Z",
        "publishedAt": "2026-06-06T19:35:03.178Z",
        "description": "Envision completed the relocation and replacement of a trash compactor unit at Moffitt Cancer Center to improve loading dock access and better support day-to-day facility operations. The scope included electrical relocation, selective demolition, a new concrete pad, bollards, dumpster stops, striping, new compactor unit coordination, and final cleaning.\n\nBecause the work took place in an active healthcare environment, our team coordinated barricades, site protection, and off-hours construction to minimize disruption while maintaining safe, organized access around the loading dock.\n",
        "beck": null
      },
      {
        "id": 179,
        "documentId": "mk6qgnwlnyfivg4uttgfwq2m",
        "title": "Moffitt Cancer Center Exterior Stairs Demo & Replace",
        "slug": "moffitt-cancer-center-exterior-stairs-demo-and-replace",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:36:46.909Z",
        "updatedAt": "2026-06-06T19:37:16.164Z",
        "publishedAt": "2026-06-06T19:37:16.212Z",
        "description": "Envision completed exterior stair improvements at Moffitt Cancer Center, including the demolition and replacement of one stairway and grout repairs at a second stairway. The work addressed ongoing water intrusion and deterioration concerns while improving the long-term performance of a frequently used exterior access point.\n\nAfter investigation, our team removed the existing stair structure to access and resolve the underlying condition, then rebuilt the stairway and completed supporting stucco patching and caulking. Due to the stair location and limited equipment access, demolition debris and concrete materials were carefully removed and transported by hand, requiring close field coordination and disciplined site management.\n\nBecause the work took place on an active healthcare campus, Envision maintained barricades and controlled access throughout the project to protect patients, staff, and visitors while keeping the surrounding area organized and accessible.",
        "beck": null
      },
      {
        "id": 182,
        "documentId": "laj6867w8yd9wp07wprw45jp",
        "title": "Moffitt Cancer Center MRC Stairway Lighting & Painting",
        "slug": "moffitt-cancer-center-mrc-stairway-lighting-and-painting",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:38:46.960Z",
        "updatedAt": "2026-06-06T19:40:07.079Z",
        "publishedAt": "2026-06-06T19:40:07.146Z",
        "description": "Envision completed stairwell improvements at Moffitt Cancer Center’s MRC, including painting, lighting upgrades, drywall repair, texture matching, and finish work at railings, door frames, and stair stringers. The project refreshed a high-use stairwell while improving visibility, durability, and the overall condition of the space.\n\nBecause the work took place in an active healthcare environment, our team coordinated off-hours construction, barricades, and clear site separation to minimize disruption for patients, staff, and visitors. The narrow stairwell required a creative access approach, with our team carefully coordinating ladder placement and work sequencing to complete elevated painting areas where a lift could not be used.",
        "beck": null
      },
      {
        "id": 184,
        "documentId": "afsby166vhbmxxm81om3fder",
        "title": "Moffitt Cancer Center MTP Asphalt Mill & Overlay",
        "slug": "moffitt-cancer-center-mtp-asphalt-mill-and-overlay",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:41:02.852Z",
        "updatedAt": "2026-06-06T19:41:40.910Z",
        "publishedAt": "2026-06-06T19:41:40.964Z",
        "description": "Envision completed an asphalt mill-and-overlay at Moffitt Cancer Center’s MTP parking lot, including new striping and parking lot accessories to improve the durability, function, and appearance of the existing parking area.\n\nTo maintain campus operations throughout construction, the work was completed in five phases across nights and weekends. Envision coordinated barricades, traffic control, layout, protection measures, and final cleaning to keep the parking area organized and accessible while the active healthcare campus remained operational.",
        "beck": null
      },
      {
        "id": 186,
        "documentId": "mch1ez2kzeg346vhc9iflqyt",
        "title": "Moffitt Cancer Center MTP Boundary Survey",
        "slug": "moffitt-cancer-center-mtp-boundary-survey",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:43:56.455Z",
        "updatedAt": "2026-06-06T19:43:57.660Z",
        "publishedAt": "2026-06-06T19:43:57.697Z",
        "description": "Envision coordinated boundary survey services for Moffitt Cancer Center’s MTP property to support accurate site documentation and future planning needs. Our team managed the field logistics, access coordination, traffic control, and final cleaning required to complete the survey work efficiently within an active healthcare campus.",
        "beck": null
      },
      {
        "id": 189,
        "documentId": "sd7kw0qjafjpvgtq9yjjkb5f",
        "title": "Moffitt Cancer Center Neuro Clinic Flooring",
        "slug": "moffitt-cancer-center-neuro-clinic-flooring",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:47:48.642Z",
        "updatedAt": "2026-06-06T19:47:58.635Z",
        "publishedAt": "2026-06-06T19:47:58.695Z",
        "description": "Envision completed flooring replacement for Moffitt Cancer Center’s Neuro Clinic in the MCB building, including the waiting room, work room, offices, and clinic corridors. In addition to flooring replacement, our SPD team self-performed painting, drywall repairs, and final cleaning to deliver a complete, polished turnover after each phase.\n\nTo maintain daytime clinic operations, the project was carefully phased for weekend execution. Envision completed one phase each weekend over eight weeks, coordinating temporary containment, air management, access controls, and work-area separation around active exam rooms and patient corridors.\n\nOriginally scheduled for 13 weeks, the project was resequenced and completed five weeks early, with all flooring successfully replaced while daily clinic operations continued uninterrupted.\n",
        "beck": null
      },
      {
        "id": 191,
        "documentId": "u6gh5nnp5vbpbku2bklle9bq",
        "title": "Moffitt Cancer Center Pigeon Control in Parking Garage",
        "slug": "moffitt-cancer-center-pigeon-control-in-parking-garage",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:50:26.248Z",
        "updatedAt": "2026-06-06T19:50:26.248Z",
        "publishedAt": "2026-06-06T19:50:26.290Z",
        "description": "Envision completed pigeon control improvements within a Moffitt Cancer Center parking garage walkway to help maintain a cleaner, more protected path of travel for staff and visitors. The scope included removal of bird-related debris, installation of overhead netting, and containment measures to support long-term deterrence.\n\nBecause the garage remained active throughout the project, our team coordinated isolated work areas, barricades, and traffic control to maintain access while safely separating construction activity from daily campus operations.",
        "beck": null
      },
      {
        "id": 193,
        "documentId": "mj38fpr4apj5csp8avdocfxi",
        "title": "Moffitt Cancer Center Thoracic Waiting Area",
        "slug": "moffitt-cancer-center-thoracic-waiting-area",
        "completed": null,
        "location": null,
        "area": null,
        "createdAt": "2026-06-06T19:52:32.328Z",
        "updatedAt": "2026-06-06T19:52:32.328Z",
        "publishedAt": "2026-06-06T19:52:32.371Z",
        "description": "Envision refreshed the Thoracic Waiting Area at Moffitt Cancer Center with new paint, door replacement, and updated door hardware. Our SPD team self-performed painting, drywall patching, sanding, and door refinishing to improve the appearance and finish of the patient-facing space.\n\nWork was completed off-hours with ICRA barriers in place to maintain a clean, controlled environment and minimize disruption for patients, staff, and visitors.\n",
        "beck": null
      }
    ]
  },
  {
    "id": 26,
    "documentId": "sutqplaehkvja2zi7suyi8sa",
    "name": "Faith",
    "slug": "faith",
    "createdAt": "2026-02-04T01:37:52.103Z",
    "updatedAt": "2026-06-03T23:20:53.784Z",
    "publishedAt": "2026-06-03T23:20:53.824Z",
    "description": "Sanctuaries, worship centers, and faith community spaces built with care and precision",
    "image": {
      "id": 17,
      "documentId": "505af17252a7430f80d38edf",
      "name": "revealing-truth-ministries-01.jpg",
      "alternativeText": null,
      "caption": null,
      "width": 5880,
      "height": 3920,
      "formats": {},
      "hash": "revealing-truth-ministries-01_6982a332",
      "ext": ".jpg",
      "mime": "image/jpeg",
      "size": 12442.51,
      "url": "https://ik.imagekit.io/pnixsw7lg/strapi-uploads/revealing-truth-ministries-01.jpg",
      "previewUrl": "https://ik.imagekit.io/pnixsw7lg/tr:n-ik_ml_thumbnail/strapi-uploads/revealing-truth-ministries-01.jpg?updatedAt=1770169140472",
      "provider": "imagekit",
      "provider_metadata": {
        "fileId": "6982a3325c7cd75eb8bee47f"
      },
      "createdAt": "2026-02-04T01:39:16.545Z",
      "updatedAt": "2026-02-07T03:53:37.657Z",
      "publishedAt": "2026-02-04T01:39:16.545Z",
      "focalPoint": null
    },
    "projects": [
      {
        "id": 133,
        "documentId": "wmovhiqcs4wff5denap1fdli",
        "title": "Revealing Truth Ministries Interior Upgrades",
        "slug": "revealing-truth-ministries-interior-upgrades",
        "completed": "2023-01-01",
        "location": "Tampa, FL",
        "area": "30,000 sqft",
        "createdAt": "2026-02-04T01:41:20.844Z",
        "updatedAt": "2026-06-04T04:24:40.565Z",
        "publishedAt": "2026-06-04T04:24:40.619Z",
        "description": "The Revealing Truth Ministries Interior Upgrades project transformed the **30,000 SF** worship center into a state-of-the-art facility. Visitors are met with a beautiful foyer upon entry, where existing circular columns were framed with drywall as a cost-effective yet modern upgrade. The main worship area, library, café, offices, and restrooms were renovated through selective demolition and implementation of new electrical systems, 2x2 LED lighting, new ceilings, room dividers, carpet tile, and a glass storefront. Additionally, buildout of backstage areas created new meeting spaces for church attendees. \n\nOur team worked closely with the owner to strategize different ways to keep costs low while implementing functional improvements to fit the growing needs of the ministry. Envision assisted with the design and aesthetic goals for this interior renovation project, providing creative yet cost-effective methods and ideas to reach the desired end product.",
        "beck": null
      },
      {
        "id": 219,
        "documentId": "v5lrmaiklk1mluzir5pd1kh8",
        "title": "Mount Olive Missionary Baptist Church - Interior & Exterior Renovation",
        "slug": "mount-olive-missionary-baptist-church-interior-and-exterior-renovation",
        "completed": "2017-01-01",
        "location": "Tampa, FL",
        "area": "12,000 SF",
        "createdAt": "2026-06-05T12:43:09.327Z",
        "updatedAt": "2026-06-08T02:43:54.793Z",
        "publishedAt": "2026-06-08T02:43:54.857Z",
        "description": "The Envision team performed interior and exterior renovations to enhance the worship experience of congregants at Mount Olive. The 12,000 SF Polk County worship center was upgraded with new flooring, expansions to the churchfront and stage, rooms and bathroom renovations, a new foyer, a complete remodel of the sanctuary, a new and modern lighting system, and a conversion of upstairs rooms into a multipurpose space. ",
        "beck": null
      }
    ]
  }
] as const;
